### ISSUE TITLE
Cancelling a query from RStudio

### ISSUE THREAD

**Issue by MarkMc1089** [r-dbi/odbc#562] opened 2023-04-21 09:59 UTC
### Issue Description and Expected Result
Unable to gracefully stop a sent query (specifically to Oracle SQL server) from RStudio. When wanting to stop a running query, only way at present is to either wait or force quit RStudio. After force quitting the query does seem to stop eventually but the time is variable, on the order of several minutes.

See the issue below, which I followed Hadley's advice on to raise here also.
https://github.com/rstudio/rstudio/issues/6287#issuecomment-1468005778

### Database
Oracle Database 19c

### Reproducible Example
Not really applicable, any long query that you subsequently want to stop before it finishes naturally.

**Comment by hadley** [comment] 2023-04-24 13:38
@detule have you look at this problem at all? It's typically a matter of ensuring that we check for user interrupts in the tight loop that retrieves data from the database.

**Comment by hadley** [comment] 2023-04-24 14:20
Duplicate of #433

**Closed by hadley** 2023-04-24 14:20 UTC
Labels: feature
