### ISSUE TITLE
"internal SAVEPOINT failed" on travis

### ISSUE THREAD

**Issue by sebschub** [r-dbi/odbc#141] opened 2017-12-11 11:07 UTC
### Issue Description and Expected Result
With PostgreSQL and when using `dbExecute()` to set a SAVEPOINT or release it, I get the error `nanodbc/nanodbc.cpp:1587: HY000: internal SAVEPOINT failed ` when querying data from the database. Strangely, I cannot reproduce this locally but only on [travis](https://travis-ci.org/sebschub/klimageodb/builds/314707309) and only with a table defined before. 

This might be an issue with some old odbc package or driver on Travis and not an issue with the odbc R package. Please feel free to close this if it is the case. It might be related to #118.

### Database
PostgreSQL v9.6 on travis

### Reproducible Example

[Travis is set-up](https://github.com/sebschub/klimageodb/blob/travis/.travis.yml) and [one table is created](https://github.com/sebschub/klimageodb/blob/travis/travis/create_tables.sql). The issue is only with this table, not with the `testtable` created below. The code

```r
con <- dbConnect(odbc::odbc(), dsn = "klimageodb")

dbWriteTable(con, "testtable", data.frame(a=10, b=20))

dbBegin(con)

dbExecute(con, "SAVEPOINT testSP;")
cat("First table 1 before\n")
dbGetQuery(con, "SELECT * FROM testtable;")
cat("First table 1 after\n")
dbExecute(con, "RELEASE SAVEPOINT testSP;")

dbExecute(con, "SAVEPOINT testSP;")
cat("First table 2 before\n")
dbGetQuery(con, "SELECT * FROM testtable;")
cat("First table 2 after\n")
dbExecute(con, "RELEASE SAVEPOINT testSP;")

dbExecute(con, "SAVEPOINT testSP;")
cat("Second table 1 before\n")
dbGetQuery(con, "SELECT * FROM site;")
cat("Second table 1 after\n")
dbExecute(con, "RELEASE SAVEPOINT testSP;")

dbExecute(con, "SAVEPOINT testSP;")
cat("Second table 2 before\n")
dbGetQuery(con, "SELECT * FROM site;")
cat("Second table 2 after\n")
dbExecute(con, "RELEASE SAVEPOINT testSP;")

dbCommit(con)

dbDisconnect(con)
```

produces the error

```
  First table 1 before
  First table 1 after
  First table 2 before
  First table 2 after
  Second table 1 before
  Error: <SQL> 'SELECT * FROM site;'
    nanodbc/nanodbc.cpp:1587: HY000: internal SAVEPOINT failed 
```

**Comment by jimhester** [comment] 2018-03-21 20:20
This seems like an issue with the driver, driver manager or database, likely caused by older versions used on travis than locally, so I am going to close this. Please re-open it if you discover this is actually an issue in the R package.

**Closed by jimhester** 2018-03-21 20:20 UTC
