### ISSUE TITLE
unable to find an inherited method for function ‘dbExistsTable’ for signature ‘"Microsoft SQL Server", "NULL"’

### ISSUE THREAD

**Issue by Fred-Wu** [r-dbi/odbc#748] opened 2024-01-19 01:58 UTC
I have been using the following codes to append data to our database for quite some time. But when I just got back from leave this time, it no longer works after I updated the package to `1.2.1`

```
    DBI::dbAppendTable(
      conn,
      DBI::SQL("xxxx.dbo.DataCollectionRaw"),
      df[chunk]
    )
```

and gives the following error message:

```
unable to find an inherited method for function ‘dbExistsTable’ for signature ‘"Microsoft SQL Server", "NULL"’
```

I also tried version `1.2.0` and it was not working too. 

So I rolled back to version '1.1.3', and it worked on this version.

**Comment by krlmlr** [comment] 2024-01-20 09:41
Introduced in r-dbi/DBI#421, surfaces here because `dbExistsTable()` in odbc makes use of `dbUnquoteIdentifier()` . Should be fixed again in the development version of the odbc package.

**Comment by hadley** [comment] 2024-01-22 13:40
Yes, this is fixed in dev odbc. We're aiming to get a CRAN release out this week. (And there are now tests for the expected behaviour in odbc that will fail if DBI changes in an incompatible way).

**Closed by hadley** 2024-01-22 13:40 UTC
