### ISSUE TITLE
Insert more than 1000 records

### ISSUE THREAD

**Issue by javierluraschi** [r-dbi/odbc#188] opened 2018-06-08 18:40 UTC
@edgararuiz mentioned this in the odbc slack channel but I couldn't find a bug open, so opening one.

This is a reprex with SQL Azure, but I  believe any driver would work...

```r
library(DBI)
con <- dbConnect(odbc::odbc(), Driver="sqlserver", Server = "javier-test.database.windows.net", Port = "1433", UID = "rstudio", PWD = .rs.askForSecret("sqlserver 5150", "Password", "Database password:"), Database = "javier-test")

ids_10k <- data.frame(a = seq_len(10000))
dbWriteTable(con, "ids_10k", ids_10k)
```

```
 Error in result_insert_dataframe(rs@ptr, values) : 
  nanodbc/nanodbc.cpp:1587: 22018: Conversion failed when converting the nvarchar value '〱㔲' to data type in 
```

**Comment by jimhester** [comment] 2019-11-15 17:08
Hmm, I unfortunately cannot reproduce this with the current devel version.

``` r
library(DBI); con <- dbConnect(odbc::odbc(), "MicrosoftSQLServer", UID = 'testuser', PWD = 'passW0rd!', database = 'test')
ids_10k <- data.frame(a = seq_len(10000))
dbWriteTable(con, "ids_10k", ids_10k)
res <- dbReadTable(con, "ids_10k")
all.equal(ids_10k, res)
#> [1] TRUE
```

<sup>Created on 2019-11-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Are you still able to reproduce it? And if so with what drivers and version of SQL Server?

**Comment by jimhester** [comment] 2019-11-15 21:45
Ok, I can reproduce this with the Simba drivers, but it works fine with the Microsoft and freeTDS drivers, so I think this might be something we should address with Simba.

``` r
library(DBI)
simba_con1 <- dbConnect(odbc::odbc(), "SimbaSQLServer", UID = 'testuser', PWD = 'passW0rd!', database = 'test')
simba_con2 <- dbConnect(odbc::odbc(), "SimbaSQLServer2", UID = 'testuser', PWD = 'passW0rd!', database = 'test')
ms_con <- dbConnect(odbc::odbc(), "MicrosoftSQLServer", UID = 'testuser', PWD = 'passW0rd!', database = 'test')
tds_con <- dbConnect(odbc::odbc(), "freeTDSSQLServer", UID = 'testuser', PWD = 'passW0rd!', database = 'test')
dbGetInfo(simba_con1)$driver.version
#> [1] "1.3.7.1026"
dbGetInfo(simba_con2)$driver.version
#> [1] "1.4.13.1013"
dbGetInfo(ms_con)$driver.version
#> [1] "17.04.0002"
dbGetInfo(tds_con)$driver.version
#> [1] "01.01.0015"

ids_10k <- data.frame(a = seq_len(10000))

dbWriteTable(simba_con1, "ids_10k", ids_10k, overwrite = TRUE)
#> Error in result_insert_dataframe(rs@ptr, values): nanodbc/nanodbc.cpp:1587: 22018: Conversion failed when converting the nvarchar value '〱㔲' to data type in
dbWriteTable(simba_con2, "ids_10k", ids_10k, overwrite = TRUE)
#> Error in result_insert_dataframe(rs@ptr, values): nanodbc/nanodbc.cpp:1587: 22018: Conversion failed when converting the nvarchar value '〱㔲' to data type in
dbWriteTable(ms_con, "ids_10k", ids_10k, overwrite = TRUE)
dbWriteTable(tds_con, "ids_10k", ids_10k, overwrite = TRUE)
```

<sup>Created on 2019-11-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment] 2020-10-21 14:32
I can no longer reproduce this, I think it must have been resolved by other changes.

``` r
library(DBI)
simba_con1 <- dbConnect(odbc::odbc(), "SimbaSQLServer", UID = 'SA', PWD = 'Password12', database = 'test')
simba_con2 <- dbConnect(odbc::odbc(), "SimbaSQLServer2", UID = 'SA', PWD = 'Password12', database = 'test')
ms_con <- dbConnect(odbc::odbc(), "MicrosoftSQLServer", UID = 'SA', PWD = 'Password12', database = 'test')
tds_con <- dbConnect(odbc::odbc(), "freeTDSSQLServer", UID = 'SA', PWD = 'Password12', database = 'test')
dbGetInfo(simba_con1)$driver.version
#> [1] "1.3.7.1026"
dbGetInfo(simba_con2)$driver.version
#> [1] "1.4.13.1013"
dbGetInfo(ms_con)$driver.version
#> [1] "17.06.0001"
dbGetInfo(tds_con)$driver.version
#> [1] "01.02.0005"

ids_10k <- data.frame(a = seq_len(10000))

dbWriteTable(simba_con1, "ids_10k", ids_10k, overwrite = TRUE)
dbWriteTable(simba_con2, "ids_10k", ids_10k, overwrite = TRUE)
dbWriteTable(ms_con, "ids_10k", ids_10k, overwrite = TRUE)
dbWriteTable(tds_con, "ids_10k", ids_10k, overwrite = TRUE)
```

<sup>Created on 2020-10-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Closed by jimhester** 2020-10-21 14:32 UTC
Labels: bug, mssql, reprex
