### ISSUE TITLE
dbRollback() does not remove Locks and in transaction created table

### ISSUE THREAD

**Issue by sebschub** [r-dbi/odbc#138] opened 2017-12-07 20:34 UTC
### Issue Description and Expected Result
`dbRollback()` apparently does not undo a after `dbBegin()` with `dbWriteTable()` created table. The table, however, is not really committed and gone after `dbDisconnect()`. So is `dbRollback()` doing a proper rollback? This behaviour happens with both stable odbc version 1.1.3 and current master. 

### Database
PostgreSQL 9.6.4 on openSUSE 42.3

### Reproducible Example

```R
library(DBI)
con <- dbConnect(odbc::odbc(), dsn = "klimageodb")
dbReadTable(con, "testtable")
#> Error: <SQL> 'SELECT * FROM "testtable"'
#>   nanodbc/nanodbc.cpp:1587: 42P01: ERROR: relation "testtable" does not exist;
#> Error while executing the query
dbBegin(con)
dbReadTable(con, "testtable")
#> Error: <SQL> 'SELECT * FROM "testtable"'
#>   nanodbc/nanodbc.cpp:1587: 42P01: ERROR: relation "testtable" does not exist;
#> Error while executing the query
dbWriteTable(con, "testtable", data.frame(a = 10, b = 20))
dbReadTable(con, "testtable")
#>    a  b
#> 1 10 20
dbRollback(con)
dbReadTable(con, "testtable")
#>    a  b
#> 1 10 20
dbDisconnect(con)
con <- dbConnect(odbc::odbc(), dsn = "klimageodb")
dbReadTable(con, "testtable")
#> Error: <SQL> 'SELECT * FROM "testtable"'
#>   nanodbc/nanodbc.cpp:1587: 42P01: ERROR: relation "testtable" does not exist;
#> Error while executing the query
dbDisconnect(con)
```

<details>
<summary>Session Info</summary>

```r
devtools::session_info()
#> Session info ------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, linux-gnu           
 ui       RStudio (1.1.383)           
 language                             
 collate  en_GB.UTF-8                 
 tz       Europe/Berlin               
 date     2017-12-07                  

Packages ----------------------------------------------------------------------------------------------------------
 package    * version date       source         
 backports    1.1.1   2017-09-25 CRAN (R 3.3.1) 
 base       * 3.3.1   2017-07-08 local          
 bit          1.1-12  2014-04-09 CRAN (R 3.3.1) 
 bit64        0.9-7   2017-05-08 CRAN (R 3.3.1) 
 blob         1.1.0   2017-06-17 CRAN (R 3.3.1) 
 callr        1.0.0   2016-06-18 CRAN (R 3.3.1) 
 clipr        0.4.0   2017-11-03 CRAN (R 3.3.1) 
 datasets   * 3.3.1   2017-07-08 local          
 DBI        * 0.7     2017-06-18 CRAN (R 3.3.1) 
 devtools     1.13.4  2017-11-09 CRAN (R 3.3.1) 
 digest       0.6.12  2017-01-27 CRAN (R 3.3.1) 
 evaluate     0.10.1  2017-06-24 CRAN (R 3.3.1) 
 graphics   * 3.3.1   2017-07-08 local          
 grDevices  * 3.3.1   2017-07-08 local          
 hms          0.4.0   2017-11-23 cran (@0.4.0)  
 htmltools    0.3.6   2017-04-28 CRAN (R 3.3.1) 
 httpuv       1.3.5   2017-07-04 CRAN (R 3.3.1) 
 jsonlite     1.5     2017-06-01 CRAN (R 3.3.1) 
 knitr        1.17    2017-08-10 CRAN (R 3.3.1) 
 magrittr     1.5     2014-11-22 CRAN (R 3.3.1) 
 memoise      1.1.0   2017-04-21 CRAN (R 3.3.1) 
 methods    * 3.3.1   2017-07-08 local          
 mime         0.5     2016-07-07 CRAN (R 3.3.1) 
 miniUI       0.1.1   2016-01-15 CRAN (R 3.3.1) 
 odbc         1.1.3   2017-10-05 CRAN (R 3.3.1) 
 pkgconfig    2.0.1   2017-03-21 CRAN (R 3.3.1) 
 R6           2.2.2   2017-06-17 CRAN (R 3.3.1) 
 Rcpp         0.12.14 2017-11-23 cran (@0.12.14)
 reprex       0.1.1   2017-01-13 CRAN (R 3.3.1) 
 rlang        0.1.4   2017-11-05 CRAN (R 3.3.1) 
 rmarkdown    1.8     2017-11-17 CRAN (R 3.3.1) 
 rprojroot    1.2     2017-01-16 CRAN (R 3.3.1) 
 rstudioapi   0.7     2017-09-07 CRAN (R 3.3.1) 
 shiny      * 1.0.5   2017-08-23 CRAN (R 3.3.1) 
 shinyjs      0.9.1   2017-06-29 CRAN (R 3.3.1) 
 stats      * 3.3.1   2017-07-08 local          
 stringi      1.1.6   2017-11-17 CRAN (R 3.3.1) 
 stringr      1.2.0   2017-02-18 CRAN (R 3.3.1) 
 tibble       1.3.4   2017-08-22 CRAN (R 3.3.1) 
 tools        3.3.1   2017-07-08 local          
 utils      * 3.3.1   2017-07-08 local          
 whisker      0.3-2   2013-04-28 CRAN (R 3.3.1) 
 withr        2.1.0   2017-11-01 CRAN (R 3.3.1) 
 xtable       1.8-2   2016-02-05 CRAN (R 3.3.1) 
 yaml         2.1.15  2017-12-01 CRAN (R 3.3.1)
```
</details>

**Comment by sebschub** [comment] 2017-12-14 10:29
Apparently, this bug has more serious results. The locks created within the transaction are not removed by `dbRollback()`! Even after disconnecting in R, the locks remain present (as well as the actual connection when viewed from pgadmin3). It seems that the odbc driver is not to blame because the same commands issued from `isql` work fine.

## Example

```R
con <- dbConnect(odbc::odbc(), dsn = "klimageo_storage")

# following is fine, devman_name has UNIQUE constraint
dbWriteTable(con, "device_manufacturer", data.frame(devman_name = "A"), append = TRUE)

# following is fine
dbBegin(con)
dbWriteTable(con, "device_manufacturer", data.frame(devman_name = "B"), append = TRUE)
dbCommit(con)

# following is fine although dbWriteTable fails
dbBegin(con)
dbWriteTable(con, "device_manufacturer", data.frame(devman_name = "A"), append = TRUE)
dbCommit(con)

# following leaves locks open!
dbBegin(con)
dbWriteTable(con, "device_manufacturer", data.frame(devman_name = "A"), append = TRUE)
dbRollback(con)

dbDisconnect(con)
```
Here the locks which remain after this code as seen from pgadmin3:

![locks_in_db](https://user-images.githubusercontent.com/464150/33987658-f0ade96e-e0c1-11e7-8539-29d0f7682b6a.png)

**Comment by jimhester** [comment] 2018-01-05 20:55
I believe this is the same issue as https://github.com/r-dbi/odbc/issues/136, and should be fixed in the devel version of ODBC.

**Comment by sebschub** [comment] 2018-01-06 22:11
Unfortunately, I can reproduce the effect with current master.

```
> devtools::session_info()
Session info -------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, linux-gnu           
 ui       RStudio (1.1.383)           
 language                             
 collate  en_GB.UTF-8                 
 tz       Europe/Berlin               
 date     2018-01-06                  

Packages -----------------------------------------------------------------------------------------------------------
 package   * version    date       source                     
 base      * 3.3.1      2017-07-08 local                      
 bit         1.1-12     2014-04-09 CRAN (R 3.3.1)             
 bit64       0.9-7      2017-05-08 CRAN (R 3.3.1)             
 blob        1.1.0      2017-06-17 CRAN (R 3.3.1)             
 datasets  * 3.3.1      2017-07-08 local                      
 DBI       * 0.7        2017-06-18 CRAN (R 3.3.1)             
 devtools    1.13.4     2017-11-09 CRAN (R 3.3.1)             
 digest      0.6.13     2017-12-14 CRAN (R 3.3.1)             
 graphics  * 3.3.1      2017-07-08 local                      
 grDevices * 3.3.1      2017-07-08 local                      
 hms         0.4.0      2017-11-23 cran (@0.4.0)              
 memoise     1.1.0      2017-04-21 CRAN (R 3.3.1)             
 methods   * 3.3.1      2017-07-08 local                      
 odbc        1.1.3.9000 2018-01-06 Github (r-dbi/odbc@f5ff7e0)
 pkgconfig   2.0.1      2017-03-21 CRAN (R 3.3.1)             
 Rcpp        0.12.14    2017-11-23 cran (@0.12.14)            
 rlang       0.1.4      2017-11-05 CRAN (R 3.3.1)             
 stats     * 3.3.1      2017-07-08 local                      
 tibble      1.3.4      2017-08-22 CRAN (R 3.3.1)             
 tools       3.3.1      2017-07-08 local                      
 utils     * 3.3.1      2017-07-08 local                      
 withr       2.1.0      2017-11-01 CRAN (R 3.3.1)             
 yaml        2.1.16     2017-12-12 CRAN (R 3.3.1) 
```

**Comment by aryoda** [comment] 2018-01-24 21:58
I have just installed the masters of `DBI`, `odbc` and `DBItest` and can reproduce exactly the same behaviour using mysql with this code snippet (background: I am trying to set up automatic unit testing of `odbc` with `DBItest` against the MS SQL Server:

```
library(DBI)
library(odbc)
library(DBItest)

DBItest::make_context(odbc::odbc(), connect_args = list(dsn="testDB", uid = "user", pwd = "password", logging = TRUE)) # mysql (old MariaDB5)
ctx <- DBItest::get_default_context()

con <- DBItest:::connect(ctx)
dbWriteTable(con, "test", data.frame(a = 0L), overwrite = TRUE)
dbBegin(con)
dbExecute(con, paste0("INSERT INTO test (a) VALUES (1)"))
dbCommit(con)
dbReadTable(con, "test")  # PRB: Seems to opens a new transaction that stays open if dbBegin/dbCommit has been called before and is not closed after disconnect!
dbDisconnect(con)

con <- DBItest:::connect(ctx)
# The following line hangs (is blocking) and I can see one open transaction in mysql with:
# SELECT * FROM information_schema.innodb_trx
dbWriteTable(con, "test", data.frame(a = 0L), overwrite = TRUE)


```

**Comment by aryoda** [comment] 2018-02-03 08:29
@sebschub Shall I open a new issue since this one is closed? Or is it possible to re-open the issue again?

**Comment by sebschub** [comment] 2018-02-08 13:50
@aryoda I think as non-developer, we cannot re-open this ticket, otherwise I would have. So yes, I think it might be good if you open a new ticket.

**Comment by dturkenk** [comment] 2018-03-06 20:21
I've also been able to reproduce this with current master against a local SQL server instance (can provide sessionInfo() if needed)

Not being able to rollback on error is definitely affecting some of our model workflows so I was curious if there were any updated status.

Thanks!

**Comment by jimhester** [comment] 2018-03-22 18:45
This should now be fixed, thank you again for the excellent reproducible example!

**Closed** 2018-03-22 18:44 UTC
Labels: bug

**Comment by aryoda** [comment] 2018-03-22 21:43
Thanks for fixing the bug.

I could  successfully execute not only the transaction-related DBI tests (`DBItest::test_transaction`) but also the whole test suite (`DBItest::test_all`) now on multiple DB engines (please ignore the Windows results - they are old):

![image](https://user-images.githubusercontent.com/11374410/37799941-892e2166-2e21-11e8-925d-96c37af7e915.png)

And the test details for mysql/MariaDB:

![image](https://user-images.githubusercontent.com/11374410/37800037-dd41bd9e-2e21-11e8-970b-a807602cce3a.png)

```
> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

Matrix products: default
BLAS: /usr/lib/atlas-base/atlas/libblas.so.3.0
LAPACK: /usr/lib/lapack/liblapack.so.3.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] tools     stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] RMariaDB_1.0-4      RPostgres_1.0-4     ggplot2_2.2.1       formattable_0.2.0.1 knitr_1.18          kableExtra_0.7.0    openxlsx_4.0.17     stringi_1.1.7      
 [9] data.table_1.10.4-3 testthat_2.0.0.9000 RSQLite_2.0         DBItest_1.5-23      odbc_1.1.5          DBI_0.8.0.9000     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16      highr_0.6         plyr_1.8.4        pillar_1.1.0      compiler_3.4.4    digest_0.6.12     bit_1.1-12        gtable_0.2.0      debugme_1.1.0    
[10] lubridate_1.7.3   viridisLite_0.2.0 memoise_1.1.0     evaluate_0.10     tibble_1.4.2      pkgconfig_2.0.1   rlang_0.2.0       cli_1.0.0         rstudioapi_0.6   
[19] yaml_2.1.14       withr_2.1.2       stringr_1.3.0     httr_1.2.1        xml2_1.1.1        htmlwidgets_0.8   desc_1.1.1        hms_0.4.2         grid_3.4.4       
[28] rprojroot_1.3-2   bit64_0.9-7       R6_2.2.2          rmarkdown_1.6     reshape2_1.4.2    callr_2.0.2       readr_1.1.1       blob_1.1.0.9001   magrittr_1.5     
[37] scales_0.4.1      backports_1.1.2   htmltools_0.3.6   assertthat_0.2.0  rvest_0.3.2       colorspace_1.3-2  lazyeval_0.2.0    munsell_0.4.3     crayon_1.3.4     

```
