### ISSUE TITLE
Issue Writing to Non-Default Schema when Table Does Not Have "_" In Name

### ISSUE THREAD

**Issue by jrisi256** [r-dbi/odbc#260] opened 2019-03-06 00:34 UTC
### Issue Description and Expected Result
When I try to use `dbWriteTable()` to write to a non-default schema, it fails when using a table name without the "_" character. The error message is:
 `Error in connection_sql_tables(conn@ptr, catalog_name = if ("catalog" %in%  : nanodbc/nanodbc.cpp:2525: 24000: [Microsoft][ODBC SQL Server Driver]Invalid cursor state `

I realize working with non-default schemas is an area under pretty active development, and I am referencing other issue threads where problems with working with non-default schemas has come up. And if I have somehow missed a solution that somebody figured out in one of these threads, I apologize.

https://github.com/r-dbi/odbc/issues/91
https://github.com/r-dbi/odbc/issues/140
https://github.com/r-dbi/odbc/issues/175
https://github.com/r-dbi/odbc/issues/191
https://github.com/r-dbi/odbc/issues/197

### Database
SQL Server 2017

### Reproducible Example
```r
library(odbc)
library(dbplyr)
library(dplyr)
library(DBI)

con <- dbConnect(odbc(),
                 Driver = "SQL SERVER",
                 Server = "SERVER_NAME,
                 Database = "DB_NAME",
                 UID = "USER_ID",
                 PWD = "PASSWORD")

#Works on default schema, no problem
dbWriteTable(con,
             "newTableIris",
             iris)

# This works
dbWriteTable(con,
             Id(schema = "EXISTING_SCHEMA",
                table = "newTableIris_"),
             iris)

# This fails with error message above
dbWriteTable(con,
             Id(schema = "EXISTING_SCHEMA",
                table = "newTableIris"),
             iris)
```

### Session Info
```r
- Session info --------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.2 (2018-12-20)
 os       Windows Server >= 2012 x64  
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/New_York            
 date     2019-03-05                  

- Packages ------------------------------------------------------------------------------------------------------------------------
 package     * version date       lib source        
 assertthat    0.2.0   2017-04-11 [1] CRAN (R 3.5.2)
 backports     1.1.3   2018-12-14 [1] CRAN (R 3.5.2)
 bit           1.1-14  2018-05-29 [1] CRAN (R 3.5.2)
 bit64         0.9-7   2017-05-08 [1] CRAN (R 3.5.2)
 blob          1.1.1   2018-03-25 [1] CRAN (R 3.5.2)
 callr         3.1.1   2018-12-21 [1] CRAN (R 3.5.2)
 cli           1.0.1   2018-09-25 [1] CRAN (R 3.5.2)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.5.2)
 DBI         * 1.0.0   2018-05-02 [1] CRAN (R 3.5.2)
 dbplyr      * 1.3.0   2019-01-09 [1] CRAN (R 3.5.2)
 desc          1.2.0   2018-05-01 [1] CRAN (R 3.5.2)
 devtools      2.0.1   2018-10-26 [1] CRAN (R 3.5.2)
 digest        0.6.18  2018-10-10 [1] CRAN (R 3.5.2)
 dplyr       * 0.8.0.1 2019-02-15 [1] CRAN (R 3.5.2)
 fs            1.2.6   2018-08-23 [1] CRAN (R 3.5.2)
 glue          1.3.0   2018-07-17 [1] CRAN (R 3.5.2)
 hms           0.4.2   2018-03-10 [1] CRAN (R 3.5.2)
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.5.2)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 3.5.2)
 odbc        * 1.1.6   2018-06-09 [1] CRAN (R 3.5.2)
 pillar        1.3.1   2018-12-15 [1] CRAN (R 3.5.2)
 pkgbuild      1.0.2   2018-10-16 [1] CRAN (R 3.5.2)
 pkgconfig     2.0.2   2018-08-16 [1] CRAN (R 3.5.2)
 pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.5.2)
 prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.5.2)
 processx      3.2.1   2018-12-05 [1] CRAN (R 3.5.2)
 ps            1.3.0   2018-12-21 [1] CRAN (R 3.5.2)
 purrr         0.3.0   2019-01-27 [1] CRAN (R 3.5.2)
 R6            2.4.0   2019-02-14 [1] CRAN (R 3.5.2)
 Rcpp          1.0.0   2018-11-07 [1] CRAN (R 3.5.2)
 remotes       2.0.2   2018-10-30 [1] CRAN (R 3.5.2)
 rlang         0.3.1   2019-01-08 [1] CRAN (R 3.5.2)
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.5.2)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.5.2)
 tibble        2.0.1   2019-01-12 [1] CRAN (R 3.5.2)
 tidyselect    0.2.5   2018-10-11 [1] CRAN (R 3.5.2)
 usethis       1.4.0   2018-08-14 [1] CRAN (R 3.5.2)
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.5.2)
```

**Comment by tavousiali** [comment] 2019-06-15 09:58
Any Updates on this Issue??

**Comment by bdforbes** [comment] 2019-06-16 08:15
My workaround to this has been to send the `INSERT` statements manually:

```r  
rs <- dbSendStatement(
  con,
  str_c("insert into OTHER_SCHEMA.nameWithoutUnderscore values (", str_c(rep("?", length(df)), collapse = ", "), ")")
)
dbBind(rs, df %>% mutate_if(is.POSIXct, as.character))
dbClearResult(rs)
```

I convert `POSIXct` to `character` because the MSSQL odbc driver doesn't like `POSIXct`.

The workaround is frustrating because I'm effectively re-implementing parts of `odbc` package because some quoting issue is broken, and I believe the fix is already in `master`, it just hasn't been released yet.

**Comment by ashleylester** [comment] 2019-08-08 11:18
I am experiencing the same issue.

**Comment by bdforbes** [comment] 2019-09-12 01:27
@jimhester Could you please advise if a fix for this issue is on the roadmap?

**Comment by soetang** [comment] 2019-10-24 11:37
The error seems to be primarily on the check in dbExistTable. 

A work-around was for us is to define our own verision of dbExistTable and then do a few small changes til odbc's write table function.  It almost an exact copy of the odbc write table:  
```
#' @inherit DBI::dbWriteTable
dbExistTable <- function(conn, name){
  
  prep_sql <- "
  IF EXISTS (
    SELECT 1 
    FROM INFORMATION_SCHEMA.TABLES 
    WHERE 
      TABLE_SCHEMA = ?schema
      AND TABLE_NAME = ?table
  ) 
  SELECT 1 AS res 
  ELSE 
  SELECT 0 AS res
  "
  
  final_sql <- DBI::sqlInterpolate(
    conn = conn
    , sql = prep_sql
    , schema = name@name["schema"]
    , table = name@name["table"]
  )
  
  res <- get_query(final_sql, conn)

  as.logical(res$res) %>% return()
}
```

```
# code based on https://github.com/r-dbi/odbc/blob/master/R/Table.R but adapted to work with schemas
#' @inherit DBI::dbWriteTable
dbWriteTable <- function(
  conn
  , name
  , value
  , overwrite=FALSE
  , append=FALSE
  , temporary = FALSE
  , row.names = NA
  , field.types = NULL
  , ...
) {
    sql_name = DBI::dbQuoteIdentifier(conn, name) 
  
    if (overwrite && append)
      stop("overwrite and append cannot both be TRUE", call. = FALSE)

    found <- dbExistTable(conn, name)
    if (found && !overwrite && !append) {
      stop("Table ", sql_name, " exists in database, and both overwrite and",
           " append are FALSE", call. = FALSE)
    }
    if (found && overwrite) {
      DBI::dbRemoveTable(conn, name)
    }
    
    values <- DBI::sqlData(conn, row.names = row.names, value[, , drop = FALSE])
    
    if (!found || overwrite) {
      sql <- DBI::sqlCreateTable(conn, name, values, field.types = field.types, row.names = FALSE, temporary = temporary)
      DBI::dbExecute(conn, sql)
    }
    
    if (nrow(value) > 0) {
      
      name <- DBI::dbQuoteIdentifier(conn, name)
      fields <- DBI::dbQuoteIdentifier(conn, names(values))
      params <- rep("?", length(fields))
      
      sql <- paste0(
        "INSERT INTO ", name, " (", paste0(fields, collapse = ", "), ")\n",
        "VALUES (", paste0(params, collapse = ", "), ")"
      )

      rs <- DBI::dbSendStatement(conn, sql)
      
      tryCatch(
        DBI::dbBind(rs, values),
        finally = DBI::dbClearResult(rs)
      )
    }
    
    invisible(TRUE)
}
```

**Comment by jimhester** [comment] 2019-11-18 14:51
I believe this is now fixed by https://github.com/r-dbi/odbc/commit/486655a903e961d12005e28bfc730f9c23488c36

**Closed by jimhester** 2019-11-18 14:51 UTC
Labels: mssql

**Comment by aryoda** [comment] 2019-12-08 17:18
Many thanks Jim :-)

I can confirm that the new CRAN version 1.2.1 (released Dec. 05, 2019) is fixing the issue finally on Microsoft SQL Server 2016.

I have tested it successfully with the drivers

- `SQL server` and
- `SQL server native client 11.0`.

**Comment by retooooo** [comment] 2020-05-22 16:09
For those, who can't upgrade to newer version, here's my workaround.
I create an insert query using this function:

`insertQry <- function(name, data) {
  paste0(
    "INSERT INTO ",
    name, 
    " (", paste(names(data), collapse = ","), ") VALUES ",
    paste(sapply(1:nrow(data), function(i) {
      paste0("(", 
             paste(sapply(names(data), function(n) {
               if(is.numeric(data[i, n])) {
                 as.character(data[i, n])
               } else {
                 paste0("'", as.character(data[i, n]), "'")
               }
             }), collapse = ","),
             ")")
    }), collapse = ",")
  )
}`

And then I execute it using dbExecute:

`dbExecute(db, insertQry('mytable', mydata))`

**Comment by retooooo** [comment] 2020-05-22 16:17
> 1111
asdasd
>

**Comment by BrazilForever11** [comment] 2023-03-21 15:49
@retooooo Thank for your suggestion, it worked for me with RJDBC and dbSendUpdate.

I wish this issue would be prioritized, I see some github post from 2016
