### ISSUE TITLE
Temporary tables not maintaned across subsequent queries

### ISSUE THREAD

**Issue by TTudino** [r-dbi/odbc#310] opened 2019-10-18 12:14 UTC
Hi Guys, I am trying to use odbc to create temporary tables in a SQL Server and then read from it but I am hitting an error. For instance, I would like to do something like:

check <- dbGetQuery(database_connection, "SELECT whatever INTO #TempTab FROM ExtTab")
update <- dbGetQuery(database_connection, "UPDATE #TempTab SET x = 0")

However, the second query returns:

[Microsoft] [ODBC Driver 17 for SQL Server][SQL Server] Invalid object name '#TempTab'

Any help???????????????

Thanks

**Comment by codref** [comment] 2019-10-18 14:48
I'm also interested in this. We use a lot of temp tables and currently the library does seem to ignore them.  
Unfortunately global temp (i.e. ##something) are a no-go.

**Comment by krlmlr** [comment] 2019-11-01 15:24
Thanks for raising this. Is this a duplicate of #127?

**Comment by jimhester** [comment] 2019-11-15 20:12
I believe this is a duplicate of #127, so I will close this issue.

**Closed by jimhester** 2019-11-15 20:12 UTC
Labels: mssql
