### ISSUE TITLE
SQL Server - Error in result_fetch(res@ptr, n) : wstring_convert::to_bytes

### ISSUE THREAD

**Issue by gitnirajky** [r-dbi/odbc#457] opened 2021-05-27 12:42 UTC
### Issue Description and Expected Result
dbGetQuery fails translating an Unicode special character stored in NVARCHAR(MAX) column in SQL Server with error message: Error in result_fetch(res@ptr, n) : wstring_convert::to_bytes

### Database
SQL Server 2016, All ODBC drivers

### Reproducible Example
Create a SQL server table with NVARCHAR column, add data as below with  special character: ( similar to <U+FFFD> but not exactly, please see image) . I can't paste the script here as special characters changes.
![image](https://user-images.githubusercontent.com/73037565/119827048-9cfa2600-bef0-11eb-9453-cebf952b2dfd.png)

Issue appears with any versions of R below:
R 4.1.0 (May, 2021)
R 4.0.5 (March, 2021)
R 4.0.4 (February, 2021)
R 4.0.3 (October, 2020)
R 4.0.2 (June, 2020)
R 4.0.1 (June, 2020)
R 4.0.0 (April, 2020) 

and any of SQL server ODBC drivers:
Tested with SQL Server below drivers and same issue
ODBC Driver 17 for SQL Server
ODBC Driver 13 for SQL Server
SQL Server

<details>
<summary>R 4.0.5, odbc package version 1.3.2, RStudio version, RStudio-1.4.1106, Windows 10 Pro machine</summary>

```r
install.packages("DBI")
install.packages("odbc")

require(odbc)

packageVersion("odbc")
#sort(unique(odbcListDrivers()[[1]]))
#con@info$driver.version

con <- dbConnect(odbc(), "SQLServerDSN")
#dbGetInfo(con)
qry<- "SELECT * FROM [dbo].[tempt_test]"

frm <- dbGetQuery(con,qry)
dbDisconnect(con)

```
</details>

**Comment by simonpcouch** [comment] 2024-03-12 17:05
I'm not able to reproduce at the moment, though I'm using <U+FFFD>:

``` r
library(DBI)
library(odbc)
con <- dbConnect(odbc(), dsn = "MicrosoftSQLServer", uid = "SA", 
                 pwd = Sys.getenv("sqlServerPass"))

packageVersion("DBI")
#> [1] '1.2.2'
packageVersion("odbc")
#> [1] '1.4.2'
con
#> <OdbcConnection> dbo@sql2
#>   Database: master
#>   Microsoft SQL Server Version: 16.00.4095

dbExecute(con, SQL("SET ANSI_NULLS ON"))
#> [1] 0
dbExecute(con, SQL("SET QUOTED_IDENTIFIER ON"))
#> [1] 0
dbExecute(con, SQL("CREATE TABLE [dbo.temp_test]([Answer] [nvarchar](100) NULL);"))
#> [1] 0
dbExecute(con, "INSERT [dbo.temp_test] ([Answer]) VALUES (N'Tricky character � test');")
#> [1] 1

dbReadTable(con, "dbo.temp_test")
#>                    Answer
#> 1 Tricky character � test

dbExecute(con, SQL("DROP TABLE [dbo.temp_test]"))
#> [1] 0
```

<sup>Created on 2024-03-12 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

I'm on MacOS aarch64, driver is Microsoft (rather than FreeTDS or Posit's Professional Drivers).

**Comment by simonpcouch** [comment] 2024-03-12 17:08
The changes in https://github.com/r-dbi/odbc/pull/553 went out in 1.3.5, which was released after this issue was filed. Is it possible that PR resolved this issue, @detule?

**Comment by detule** [comment] 2024-03-13 01:06
Hey Simon,

Was either fixed by that PR or alternatively, may have been related to a dated tool chain.  Either way, I think we can close in absence of recent reports.

Thanks!

**Closed** 2024-03-13 12:07 UTC
Labels: bug, mssql, encoding 🔤
