### ISSUE TITLE
Empty data.frame result from `dbGetQuery` if there is an `IF` statement in SQL Server query

### ISSUE THREAD

**Issue by jmpanfil** [r-dbi/odbc#573] opened 2023-05-23 19:58 UTC
### Issue Description and Expected Result
`dbGetQuery()` returns an empty data.frame if there is an `IF` clause in the sql query.

### Database
SQL Server 2018

### Reproducible Example
Unfortunately, impossible to include the full query.

Essentially, there's a declared table `@Results` that has several select statements inserted into it.
For the final `insert into @Results select ....`, if add I add ```IF @some_var = 'thing'``` and then the exact same ```insert into select ...```,
```dbGetQuery()``` returns an empty data.frame with, 0 obs of 0 variables. Removing that `IF` from the sql query results in a proper filled data.frame with several columns.

I have `SET NOCOUNT ON` as mentioned [in this issue ](https://github.com/r-dbi/odbc/issues/173).

For a little better schematics of the whole query, here's the basic idea. The following works:
```
SET NOCOUNT ON
declare @Results table(...);
INSERT INTO @Results (...)
    SELECT ... from table1;

INSERT INTO @Results (...)
    SELECT ... from table2;

select * from @Results
```
This code returns a fully populated data.frame in R with `dbGetQuery()`.

However, if we add in an `IF` before that second `insert into` like

```
IF something
INSERT INTO @Results (...)
    SELECT ... from table2;
```

Then the resulting `data.frame` in R is 0 obs of 0 columns.

<details>
<summary>Session Info</summary>

```r
R version 4.2.2 (2022-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux 8.8 (Ootpa)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblasp-r0.3.15.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] odbc_1.3.4

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.10      magrittr_2.0.3   hms_1.1.3        rappdirs_0.3.3   bit_4.0.5        here_1.0.1       R6_2.5.1         rlang_1.1.0     
 [9] fansi_1.0.4      blob_1.2.4       tools_4.2.2      utf8_1.2.3       cli_3.6.1        DBI_1.1.3        askpass_1.1      yaml_2.3.7      
[17] bit64_4.0.5      assertthat_0.2.1 rprojroot_2.0.3  tibble_3.2.1     lifecycle_1.0.3  keyring_1.3.1    readr_2.1.4      tzdb_0.4.0      
[25] vctrs_0.6.2      glue_1.6.2       stringi_1.7.12   compiler_4.2.2   pillar_1.9.0     filelock_1.0.2   sodium_1.2.1     renv_0.16.0     
[33] pkgconfig_2.0.3 
```
</details>

**Comment by hadley** [comment] 2023-06-07 16:06
Can you try and create a simpler query that still illustrates the problem? As it is, it's unlikely we'll be able to reproduce and thus fix the bug.

**Comment by hadley** [comment] 2023-12-12 14:38
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2023-12-12 14:38 UTC
