### ISSUE TITLE
Error converting data type varchar to numeric when writing more than 1024 numeric digits rows to SQL SERVER

### ISSUE THREAD

**Issue by shizidushu** [r-dbi/odbc#257] opened 2019-02-21 06:51 UTC
### Database
SQL Server 2016

### Reproducible Example
``` r
numbers <- c(0.12, 0.09, 0.09, 0.09, 0.15, 0.03, 0.136, 0.08, 0.32, 0.08, 
              0.08, 0.02, 0.08, 0.08, 0.18, 0.136, 0.112, 0.26, 0.12, 0.02, 
              0.1, 0.01, 0.02, 0.4, 0.06, 0.06, 0.112, 0.08, 0.01, 0.02, 0.04, 
              0.24, 0.05, 0.09, 0.062, 0.2, 0.03, 0.03, 0.112, 0.28, 0.136, 
              0.112, 0.05, 0.05, 0.04, 0.26, 0.09, 0.06, 0.01, 0.12, 0.09, 
              0.12, 0.04, 0.04, 0.04, 0.07, 0.07, 0.17, 0.14, 0.04, 0.08, 0.05, 
              0.06, 0.06, 0.07, 0.06, 0.17, 0.07, 0.07, 0.06, 0.035, 0.035, 
              0.1, 0.08, 0.07, 0.07, 0.07, 0.07, 0.03, 0.6, 0.06, 0.05, 0.06, 
              0.16, 0.12, 0.03, 0.1, 0.09, 0.09, 0.03, 0.06, 0.04, 0.04, 0.06, 
              0.06, 0.16, 0.02, 0.16, 0.16, 0.01, 0.01, 0.01, 0.03, 0.09, 0.1, 
              0.12, 0.06, 0.08, 0.1, 0.14, 0.08, 0.09, 0.09, 0.06, 0.08, 0.06, 
              0.06, 0.02, 0.08, 0.04, 0.06, 0.03, 0.11, 0.05, 0.01, 0.01, 0.1, 
              0.28, 0.03, 0.04, 0.77, 0.03, 0.06, 0.06, 0.1, 0.1, 0.1, 0.1, 
              0.1, 0.01, 0.04, 0.15, 0.03, 0.05, 0.05, 0.2, 0.06, 0.2, 0.09, 
              0.07, 0.1, 0.08, 0.04, 0.08, 0.06, 0.06, 0.08, 0.06, 0.07, 0.08, 
              0.07, 0.06, 0.08, 0.253, 0.05, 0.05, 0.57, 0.07, 0.09, 0.085, 
              0.085, 0.08, 0.08, 0.1, 0.08, 0.12, 0.1, 0.06, 0.04, 0.092, 0.1, 
              0.05, 0.1, 0.04, 0.04, 0.04, 0.08, 0.03, 0.1, 0.05, 0.08, 0.03, 
              0.06, 0.06, 0.04, 0.092, 0.1, 0.1, 0.07, 0.05, 0.08, 0.03, 0.06, 
              0.06, 0.032, 0.06, 0.03, 0.024, 0.05, 0.08, 0.03, 0.06, 0.25, 
              0.08, 0.09, 0.08, 0.08, 0.263, 0.07, 0.1, 0.03, 0.04, 0.06, 0.053, 
              0.06, 0.053, 0.042, 0.09, 0.045, 0.08, 0.017, 0.04, 0.012, 0.055, 
              0.1, 0.055, 0.08, 0.1, 0.1, 0.04, 0.03, 0.03, 0.09, 0.07, 0.053, 
              0.05, 0.042, 0.053, 0.05, 0.042, 0.06, 0.06, 0.04, 0.04, 0.08, 
              0.1, 0.07, 0.09, 0.085, 0.196, 0.13, 0.09, 0.04, 0.06, 0.13, 
              0.09, 0.03, 0.1, 0.06, 0.1, 0.05, 0.1, 0.1, 0.08, 0.09, 0.08, 
              0.081, 0.1, 0.1, 0.1, 0.09, 0.08, 0.07, 0.06, 0.032, 0.06, 0.085, 
              0.35, 0.09, 0.032, 0.08, 0.085, 0.65, 0.1, 0.09, 0.1, 0.08, 0.04, 
              0.05, 0.06, 0.06, 0.1, 0.055, 0.032, 0.07, 0.05, 0.065, 0.012, 
              0.012, 0.012, 0.012, 0.012, 0.012, 0.1, 0.055, 0.056, 0.08, 0.063, 
              0.112, 0.1, 0.06, 0.09, 0.03, 0.14, 0.09, 0.09, 0.25, 0.08, 0.05, 
              0.07, 0.03, 0.024, 0.09, 0.06, 0.042, 0.055, 0.092, 0.08, 0.1, 
              0.1, 0.6, 0.6, 0.3, 0.6, 0.3, 0.8, 0.3, 0.8, 0.6, 0.3, 0.6, 0.1, 
              0.8, 0.05, 0.4, 0.6, 0.02, 0.01, 0.6, 0.03, 0.01, 0.04, 0.3, 
              0.6, 0.6, 0.3, 0.6, 0.6, 0.1, 0.6, 0.6, 0.6, 0.02, 0.8, 0.8, 
              0.05, 0.05, 0.05, 0.8, 0.03, 0.3, 0.11, 0.02, 0.1, 0.01, 0.02, 
              0.02, 0.03, 0.8, 0.3, 0.3, 0.8, 0.3, 0.8, 0.6, 0.02, 0.8, 0.02, 
              0.6, 0.14, 0.8, 0.03, 0.03, 0.03, 0.04, 0.6, 0.02, 0.39, 0.39, 
              0.02, 0.08, 0.1, 0.06, 0.8, 0.02, 0.3, 0.8, 0.8, 0.8, 0.01, 0.8, 
              0.8, 0.3, 0.05, 0.11, 0.11, 0.02, 0.1, 0.1, 0.01, 0.3, 0.05, 
              0.05, 0.05, 0.05, 0.05, 0.8, 0.3, 0.7, 0.81, 0.5, 0.8, 0.8, 0.05, 
              0.52, 0.14, 0.3, 0.14, 0.41, 0.05, 0.01, 0.14, 0.1, 0.12, 0.05, 
              0.05, 0.14, 0.3, 0.02, 0.02, 0.02, 0.02, 0.02, 0.1, 0.05, 0.02, 
              0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.07, 0.07, 0.02, 0.41, 
              0.01, 0.04, 0.1, 0.35, 0.24, 0.32, 0.05, 0.29, 0.24, 0.14, 0.41, 
              0.05, 0.05, 0.05, 0.134, 0.3, 0.02, 0.41, 0.03, 0.3, 0.06, 0.32, 
              0.32, 3, 0.05, 0.47, 0.41, 0.11, 0.6, 0.03, 0.3, 0.38, 0.14, 
              0.04, 0.04, 0.14, 0.3, 0.01, 0.01, 0.03, 0.02, 0.07, 0.05, 0.05, 
              0.06, 0.1, 1.1, 0.025, 0.03, 0.02, 0.3, 0.06, 0.75, 0.3, 0.06, 
              0.75, 0.05, 0.09, 0.28, 0.06, 0.12, 0.08, 0.025, 0.08, 0.02, 
              0.3, 0.1, 0.02, 0.3, 0.13, 0.26, 0.28, 0.3, 0.3, 0.01, 0.3, 0.3, 
              0.2, 0.02, 0.06, 0.14, 0.3, 0.8, 0.3, 0.04, 0.025, 0.025, 0.025, 
              0.025, 0.05, 0.05, 0.3, 0.2, 0.15, 0.06, 0.09, 0.07, 0.29, 0.29, 
              0.45, 0.02, 0.02, 0.041, 0.02, 0.3, 0.07, 0.01, 0.01, 0.09, 0.01, 
              0.06, 0.02, 0.06, 0.21, 0.09, 0.02, 0.97, 0.78, 0.14, 0.14, 0.05, 
              0.3, 0.04, 0.5, 0.04, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 
              0.08, 0.08, 0.1, 0.08, 0.08, 0.08, 0.08, 0.1, 0.08, 0.08, 0.08, 
              0.1, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 
              0.08, 0.08, 0.08, 0.04, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 
              0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 
              0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 
              0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 
              0.1, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.2, 0.08, 0.08, 
              0.08, 0.08, 0.08, 0.08, 0.1, 0.08, 0.43, 1.06, 0.62, 0.3, 0.36, 
              0.13, 0.13, 0.3, 0.15, 0.15, 0.3, 0.27, 0.15, 0.34, 0.6, 0.15, 
              0.13, 0.13, 0.15, 0.17, 0.15, 0.3, 0.09, 0.15, 0.06, 0.15, 0.08, 
              0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 
              0.1, 0.1, 0.1, 0.1, 0.055, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 
              0.1, 0.1, 0.1, 0.24, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 
              0.1, 0.1, 0.1, 0.1, 0.1, 0.055, 0.1, 0.1, 0.1, 0.007, 0.1, 0.1, 
              0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.19, 0.47, 0.05, 
              0.05, 0.07, 0.04, 0.03, 0.08, 0.06, 0.06, 0.04, 0.09, 0.11, 0.22, 
              0.07, 0.07, 0.07, 0.18, 0.04, 0.04, 0.1, 0.06, 0.06, 0.22, 0.06, 
              0.1, 0.1, 0.09, 0.59, 0.08, 0.06, 0.21, 0.03, 0.05, 0.03, 0.05, 
              0.06, 0.03, 0.05, 0.04, 0.24, 0.03, 0.04, 0.04, 0.14, 0.05, 0.14, 
              0.03, 0.03, 0.04, 0.02, 0.11, 0.09, 0.06, 0.09, 0.07, 0.07, 0.06, 
              0.1, 0.06, 0.07, 0.03, 0.04, 0.08, 0.11, 0.05, 0.05, 0.08, 0.08, 
              0.3, 0.07, 0.18, 0.06, 0.04, 0.05, 0.1, 0.06, 0.24, 0.06, 0.09, 
              0.14, 0.14, 0.06, 0.02, 0.09, 0.09, 0.08, 0.07, 0.04, 0.03, 0.07, 
              0.09, 0.04, 0.09, 0.1, 0.04, 0.07, 0.09, 0.3, 0.04, 0.03, 0.04, 
              0.3, 0.04, 0.05, 0.03, 0.04, 0.06, 0.04, 0.07, 0.07, 0.04, 0.04, 
              0.06, 0.3, 0.06, 0.13, 0.09, 0.3, 0.05, 0.04, 0.08, 0.01, 0.04, 
              0.09, 0.3, 0.03, 0.03, 0.03, 0.03, 0.04, 0.03, 0.18, 0.09, 0.07, 
              0.59, 0.09, 0.11, 0.04, 0.2, 0.03, 0.03, 0.041, 0.14, 0.03, 0.03, 
              0.06, 0.05, 0.1, 0.05, 0.06, 0.01, 0.039, 0.027, 0.05, 0.021, 
              0.18, 0.2, 0.04, 0.06, 0.08, 0.09, 0.21, 0.04, 0.09, 0.03, 0.06, 
              0.1, 0.18, 0.1, 0.05, 0.09, 0.06, 0.01, 0.04, 0.17, 0.03, 0.04, 
              0.04, 0.14, 0.05, 0.16, 0.14, 0.05, 0.04, 0.04, 0.04, 0.14, 0.1, 
              0.04, 0.27, 0.3, 0.079, 0.05, 0.05, 0.07, 0.04, 0.04, 0.04, 0.04, 
              0.04, 0.12, 0.09, 0.21, 0.06, 0.06, 0.03, 0.31, 0.1, 0.04, 0.03, 
              0.08, 0.08, 0.08, 0.04, 0.04, 0.09, 0.04, 0.14, 0.03, 0.03, 0.03, 
              0.08, 0.06, 0.06, 0.1, 0.08, 0.09, 0.08, 0.28, 0.03, 0.03, 0.08, 
              0.04, 0.09, 0.07, 0.04, 0.05, 0.1, 0.07, 0.06, 0.03, 0.02, 0.07, 
              0.05, 0.09, 0.03, 0.06, 0.19, 0.04, 0.03, 0.09, 0.07, 0.05, 0.07, 
              0.03, 0.05, 0.14, 0.06, 0.05, 0.106, 0.08, 0.07, 0.07, 0.06, 
              0.03, 0.1, 0.19, 0.05, 0.15, 0.09, 0.22, 0.22, 0.5, 0.06, 0.05, 
              0.2, 0.01, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.15, 0.15, 0.3, 
              0.02, 0.4, 0.14, 0.15, 0.37, 0.007, 0.007, 0.007, 0.007, 0.1, 
              0.007, 0.3, 0.007, 0.007, 0.05, 0.07, 0.07, 0.02, 0.15, 0.3, 
              0.1, 0.07, 0.3, 0.02, 0.1, 0.3, 0.1, 0.02, 0.03, 0.01, 0.01, 
              0.2, 0.02, 0.1, 0.01, 0.06, 0.08, 0.07, 0.07, 0.07, 0.04, 0.5, 
              0.2, 0.1, 0.36, 0.4, 0.1, 0.04, 0.03, 0.1, 0.05, 0.02, 0.15, 
              0.1, 0.1, 0.1, 0.22, 0.1, 0.1, 0.12, 0.12, 0.03, 0.5, 0.05, 0.1, 
              0.1, 0.1, 0.5, 0.1, 0.5, 0.15, 0.1, 0.08, 0.05, 0.08, 0.09, 0.01, 
              0.01, 0.01, 0.1, 0.1, 0.1, 0.3, 0.1, 0.2, 0.09, 0.14, 0.5, 0.09, 
              0.3, 0.5, 0.2, 0.1, 0.09, 0.1, 0.2, 0.14, 0.09, 0.2, 0.1, 0.15, 
              0.05, 0.02, 0.2, 0.01, 0.03, 0.02, 0.01, 0.01, 0.02, 0.1, 0.1, 
              0.2, 0.03, 0.09, 0.15, 0.09, 0.06, 0.06, 0.2, 0.15, 0.09, 0.01, 
              0.2, 0.08, 0.14, 0.09, 0.15, 0.09, 0.2, 0.39, 0.01, 0.5, 0.1, 
              0.09, 0.01, 0.01, 0.2, 0.02, 0.09, 0.01, 0.01, 0.2, 0.09, 0.02, 
              0.02, 0.1, 0.5, 0.09, 0.09, 0.14, 0.14, 0.15, 0.2, 0.02, 0.3, 
              0.01, 0.5, 0.5, 0.1, 0.2, 0.09, 0.01, 0.01, 0.01, 0.1, 0.1, 0.15, 
              0.3, 0.1, 0.3, 0.2, 0.1, 0.31, 0.3, 0.2, 0.1, 0.08, 0.09, 0.1, 
              0.01, 0.1, 0.04, 0.2, 0.14, 0.09, 0.09, 0.14, 0.3, 0.09, 0.02, 
              0.02, 0.01, 0.01, 0.01, 0.01, 0.01, 0.02, 0.02, 0.02, 0.02, 0.1, 
              0.1, 0.035, 0.07, 0.083, 0.06, 0.01, 0.01, 0.4, 0.07, 0.04, 0.06, 
              0.13, 0.1, 0.04, 0.06, 0.06, 0.2, 0.09, 0.13, 0.06, 0.01, 0.07, 
              0.07, 0.01, 0.01, 0.01, 0.035, 0.06, 0.6, 0.1, 0.06, 0.08, 0.08, 
              0.08, 0.14, 0.05, 0.05, 0.05, 0.05, 0.03, 0.06, 0.03, 0.03, 0.08, 
              0.06, 0.06, 0.06, 0.08, 0.08, 0.14, 0.04, 0.27, 0.08, 0.08, 0.08, 
              0.2, 0.01, 0.2, 0.2, 0.07, 0.007, 0.2, 0.02, 0.2, 0.1)

test_tb <- tibble::tibble(x = numbers )

library(DBI)
dw <- config::get("datawarehouse", file = "~/config.yml")
con <- DBI::dbConnect(odbc::odbc(),
                      Driver = dw$driver,
                      Server = dw$server,
                      UID    = dw$uid,
                      PWD    = dw$pwd,
                      Port   = dw$port,
                      Database = dw$database,
                      .connection_string = "Language=English;AutoTranslate=Yes;"
)
dbWriteTable(con, "temp_table_001", value = test_tb, append = TRUE, field.types = c(x = "decimal(18,4)"))
#> Error in result_insert_dataframe(rs@ptr, values): nanodbc/nanodbc.cpp:1587: 42000: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Error converting data type varchar to numeric.
dbWriteTable(con, "temp_table_001", value = test_tb[1:1024, ], append = TRUE, field.types = c(x = "decimal(18,4)"))
dbWriteTable(con, "temp_table_001", value = test_tb[1:1025, ], append = TRUE, field.types = c(x = "decimal(18,4)"))
#> Error in result_insert_dataframe(rs@ptr, values): nanodbc/nanodbc.cpp:1587: 42000: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Error converting data type varchar to numeric.

dbSendQuery(con, "drop table temp_table_001")
#> <OdbcResult>
#>   SQL  drop table temp_table_001
#>   ROWS Fetched: 0 [complete]
#>        Changed: 0
dbDisconnect(con)
#> Warning in connection_release(conn@ptr): There is a result object still in use.
#> The connection will be automatically released when it is closed
```

<sup>Created on 2019-02-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> Warning in system("timedatectl", intern = TRUE): running command
#> 'timedatectl' had status 1
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.5.2 (2018-12-20)
#>  os       Debian GNU/Linux 9 (stretch)
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       Etc/UTC                     
#>  date     2019-02-21                  
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package     * version    date       lib source                      
#>  assertthat    0.2.0      2017-04-11 [1] CRAN (R 3.5.2)              
#>  backports     1.1.3      2018-12-14 [1] CRAN (R 3.5.2)              
#>  bit           1.1-14     2018-05-29 [1] CRAN (R 3.5.2)              
#>  bit64         0.9-7      2017-05-08 [1] CRAN (R 3.5.2)              
#>  blob          1.1.1      2018-03-25 [1] CRAN (R 3.5.2)              
#>  callr         3.1.1      2018-12-21 [1] CRAN (R 3.5.2)              
#>  cli           1.0.1      2018-09-25 [1] CRAN (R 3.5.2)              
#>  config        0.3        2018-03-27 [1] CRAN (R 3.5.2)              
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.5.2)              
#>  DBI         * 1.0.0      2018-05-02 [1] CRAN (R 3.5.2)              
#>  desc          1.2.0      2018-05-01 [1] CRAN (R 3.5.2)              
#>  devtools      2.0.1      2018-10-26 [1] CRAN (R 3.5.2)              
#>  digest        0.6.18     2018-10-10 [1] CRAN (R 3.5.2)              
#>  evaluate      0.12       2018-10-09 [1] CRAN (R 3.5.2)              
#>  fs            1.2.6      2018-08-23 [1] CRAN (R 3.5.2)              
#>  glue          1.3.0      2018-07-17 [1] CRAN (R 3.5.2)              
#>  highr         0.7        2018-06-09 [1] CRAN (R 3.5.2)              
#>  hms           0.4.2      2018-03-10 [1] CRAN (R 3.5.2)              
#>  htmltools     0.3.6      2017-04-28 [1] CRAN (R 3.5.2)              
#>  knitr         1.21       2018-12-10 [1] CRAN (R 3.5.2)              
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.5.2)              
#>  memoise       1.1.0      2017-04-21 [1] CRAN (R 3.5.2)              
#>  odbc          1.1.6      2018-06-09 [1] CRAN (R 3.5.2)              
#>  pillar        1.3.1      2018-12-15 [1] CRAN (R 3.5.2)              
#>  pkgbuild      1.0.2      2018-10-16 [1] CRAN (R 3.5.2)              
#>  pkgconfig     2.0.2      2018-08-16 [1] CRAN (R 3.5.2)              
#>  pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.5.2)              
#>  prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.5.2)              
#>  processx      3.2.1      2018-12-05 [1] CRAN (R 3.5.2)              
#>  ps            1.3.0      2018-12-21 [1] CRAN (R 3.5.2)              
#>  R6            2.3.0      2018-10-04 [1] CRAN (R 3.5.2)              
#>  Rcpp          1.0.0      2018-11-07 [1] CRAN (R 3.5.2)              
#>  remotes       2.0.2      2018-10-30 [1] CRAN (R 3.5.2)              
#>  rlang         0.3.1.9000 2019-02-19 [1] Github (r-lib/rlang@7243c6d)
#>  rmarkdown     1.11       2018-12-08 [1] CRAN (R 3.5.2)              
#>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.2)              
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.5.2)              
#>  stringi       1.2.4      2018-07-20 [1] CRAN (R 3.5.2)              
#>  stringr       1.3.1      2018-05-10 [1] CRAN (R 3.5.2)              
#>  testthat      2.0.1      2018-10-13 [1] CRAN (R 3.5.2)              
#>  tibble        2.0.1      2019-01-12 [1] CRAN (R 3.5.2)              
#>  usethis       1.4.0      2018-08-14 [1] CRAN (R 3.5.2)              
#>  withr         2.1.2      2018-03-15 [1] CRAN (R 3.5.2)              
#>  xfun          0.4        2018-10-23 [1] CRAN (R 3.5.2)              
#>  yaml          2.2.0      2018-07-25 [1] CRAN (R 3.5.2)              
#> 
#> [1] /usr/local/lib/R/site-library
#> [2] /usr/local/lib/R/library
```

</details>

**Comment by jimhester** [comment] 2019-11-15 18:58
This seems to be the same issue as #217, but as mentioned I cannot reproduce this behavior on macOS with any of the available SQL Server drivers.

I am going to close this issue as a duplicate.

**Closed by jimhester** 2019-11-15 18:58 UTC
Labels: mssql
