### ISSUE TITLE
In the latest version of odbc, temporary db tables are visible across sessions.

### ISSUE THREAD

**Issue by bergarog** [r-dbi/odbc#735] opened 2024-01-18 10:17 UTC
### Database
Microsoft SQL Server 2017 (RTM-CU12) (KB4464082) - 14.0.3045.24 (X64)   Oct 18 2018 23:11:05   Copyright (C) 2017 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

### Description 1
I am starting a new R session and creating a temporary table in a Microsoft SQL Server database.

```
version
#>                _                                
#> platform       x86_64-w64-mingw32               
#> arch           x86_64                           
#> os             mingw32                          
#> crt            ucrt                             
#> system         x86_64, mingw32                  
#> status                                          
#> major          4                                
#> minor          3.2                              
#> year           2023                             
#> month          10                               
#> day            31                               
#> svn rev        85441                            
#> language       R                                
#> version.string R version 4.3.2 (2023-10-31 ucrt)
#> nickname       Eye Holes
packageVersion("odbc")
#> [1] '1.4.1'
packageVersion("DBI")
#> [1] '1.2.1'
packageVersion("dplyr")
#> [1] '1.1.4'

conn <- DBI::dbConnect(odbc::odbc(), .connection_string = "Driver=SQL Server; Server=MYSERVER; Database=MYDB;")

x <- tibble::tibble(
  x = c(1, 2, 3),
  y = c(4, 5, 6)
)

DBI::dbExistsTable(conn, "#x")
#> [1] FALSE

dplyr::copy_to(conn, x, "x", temporary = TRUE)
#> Created a temporary table named #x
```
### Description 2
I leave the first R session running and start a second R session, then repeat the steps.

```
version
#>                _                                
#> platform       x86_64-w64-mingw32               
#> arch           x86_64                           
#> os             mingw32                          
#> crt            ucrt                             
#> system         x86_64, mingw32                  
#> status                                          
#> major          4                                
#> minor          3.2                              
#> year           2023                             
#> month          10                               
#> day            31                               
#> svn rev        85441                            
#> language       R                                
#> version.string R version 4.3.2 (2023-10-31 ucrt)
#> nickname       Eye Holes
packageVersion("odbc")
#> [1] '1.4.1'
packageVersion("DBI")
#> [1] '1.2.1'
packageVersion("dplyr")
#> [1] '1.1.4'

conn <- DBI::dbConnect(odbc::odbc(), .connection_string = "Driver=SQL Server; Server=MYSERVER; Database=MYDB;")

x <- tibble::tibble(
  x = c(1, 2, 3),
  y = c(4, 5, 6)
)

DBI::dbExistsTable(conn, "#x")
#> [1] TRUE

dplyr::copy_to(conn, x, "x", temporary = TRUE)
#> Created a temporary table named #x
#> Error in `db_copy_to()`:
#> ! Can't copy to table "#x".
#> Caused by error in `dplyr::db_write_table()`:
#> ! Can't write table table "#x".
#> Caused by error:
#> ! Table <Id> "#x" exists in database, and both overwrite and append are FALSE
```

### Description 3
How is the temporary table #x visible for the second R session?
I'm starting another R session with an older R version, and here everything works as expected.

```
version
#>                _                                
#> platform       x86_64-w64-mingw32               
#> arch           x86_64                           
#> os             mingw32                          
#> crt            ucrt                             
#> system         x86_64, mingw32                  
#> status                                          
#> major          4                                
#> minor          3.1                              
#> year           2023                             
#> month          06                               
#> day            16                               
#> svn rev        84548                            
#> language       R                                
#> version.string R version 4.3.1 (2023-06-16 ucrt)
#> nickname       Beagle Scouts
packageVersion("odbc")
#> [1] '1.3.5'
packageVersion("DBI")
#> [1] '1.1.3'
packageVersion("dplyr")
#> [1] '1.1.3'

conn <- DBI::dbConnect(odbc::odbc(), .connection_string = "Driver=SQL Server; Server=MYSERVER; Database=MYDB;")

x <- tibble::tibble(
  x = c(1, 2, 3),
  y = c(4, 5, 6)
)

DBI::dbExistsTable(conn, "#x")
#> [1] FALSE

dplyr::copy_to(conn, x, "x", temporary = TRUE)
#> Created a temporary table named #x
```

**Comment by hadley** [comment] 2024-01-18 14:03
Duplicate of #719, which has been fixed and will be included in the next release.

**Closed by hadley** 2024-01-18 14:03 UTC
