### ISSUE TITLE
Error: nanodbc/nanodbc.cpp:983: 00000: [unixODBC][Driver Manager] Can't open lib: file not found 

### ISSUE THREAD

**Issue by stevecondylios** [r-dbi/odbc#356] opened 2020-04-09 14:47 UTC
Hi there

### Problem + example

This
```R
library(DBI)
con <- dbConnect(odbc::odbc(), driver = Sys.getenv("DRIVER_PATH"), 
                 server = "aus_net", database = "ice", 
                  uid = Sys.getenv("USERNAME"), pwd = Sys.getenv("PASSWORD"))
```

ran perfectly in a previous R version, but after updating R (and all packages) to `3.6.3` today, I now see the following error message

```R
con <- dbConnect(odbc::odbc(), driver = Sys.getenv("DRIVER_PATH"), 
                 server = "aus_net", database = "ice", 
                  uid = Sys.getenv("USERNAME"), pwd = Sys.getenv("PASSWORD"))

Error: nanodbc/nanodbc.cpp:983: 00000: [unixODBC][Driver Manager]
Can't open lib '/Applications/IBM/informix/lib/cli/iclit09b.dylib' : file not found 
```

yet

```R
system("ls /Applications/IBM/informix/lib/cli/")
# [1] iclit09b.dylib
```

### What I've tried

Noting

```R
odbc::odbc() %>% class
# [1] "OdbcDriver"
# attr(,"package")
# [1] "odbc"
```

running `getMethod("dbConnect", "OdbcDriver")` allows us to trace the same error message to

```R
        con <- odbc:::OdbcConnection(dsn = dsn, ..., timezone = timezone, 
            timezone_out = timezone_out, encoding = encoding, 
            bigint = bigint, timeout = timeout, driver = driver, 
            server = server, database = database, uid = uid, 
            pwd = pwd, dbms.name = dbms.name, .connection_string = .connection_string)
```

then via `odbc:::OdbcConnection` to 

```
    ptr <- odbc:::odbc_connect(connection_string, timezone = timezone, 
        timezone_out = timezone_out, encoding = encoding, bigint = bigint, 
        timeout = timeout)
```

which leads to c++ code, i.e.

```
odbc:::odbc_connect
function (connection_string, timezone = "", timezone_out = "", 
    encoding = "", bigint = 0L, timeout = 0L) 
{
    .Call(`_odbc_odbc_connect`, connection_string, timezone, 
        timezone_out, encoding, bigint, timeout)
}
<bytecode: 0x7fac7f23d5a0>
<environment: namespace:odbc>
```

where i am not sure how to trace any further.

Note at this point `connection_string ` is 

```R
"driver={/Applications/IBM/informix/lib/cli/iclit09b.dylib};server=trsprd_ausds_net;database=eunice;uid=us3rname;pwd=passw0rd"
```

I also tried 
```R
"driver=/Applications/IBM/informix/lib/cli/iclit09b.dylib;server=trsprd_ausds_net;database=eunice;uid=us3rname;pwd=passw0rd"
```
 (for good measure)

### What to try next

From here i am somewhat stuck and not sure how to proceed. SO question to same effect [here](https://stackoverflow.com/questions/61119775/odbc-dbconnect-cant-open-lib-file-not-found-but-file-is-there)

**Comment by jimhester** [comment] 2020-04-09 14:59
The issue is likely with a shared library the dynamic library depends on that is not found. If you run `otool -L /Applications/IBM/informix/lib/cli/iclit09b.dylib` it may point you towards which one is missing.

**Comment by stevecondylios** [comment] 2020-04-09 15:04
Thanks for the fast reply, really appreciate it. 

I guessed the issue was at R or library level (or c++ level) since everything worked before I updated R/libraries but not afterwards. But I know nothing about how db drivers/connections operate under the hood - I usually follow the instructions and hope (pray) for the best! 

Thanks for the `otool -L /Applications/IBM/informix/lib/cli/iclit09b.dylib` tip - I will do so now - thanks again

**Comment by stevecondylios** [comment] 2020-04-09 18:43
Thanks again for the pointer. `otool -L /Applications/IBM/informix/lib/cli/iclit09b.dylib` returns

```
/Applications/IBM/informix/lib/cli/iclit09b.dylib:
	iclit09b.dylib (compatibility version 0.0.0, current version 0.0.0)
	sobj4/igl4a304.dylib (compatibility version 0.0.0, current version 0.0.0)
	sobj4/iglxa304.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
	/System/Library/Frameworks/DirectoryService.framework/Versions/A/DirectoryService (compatibility version 1.0.0, current version 1.0.0)
```
Versions appear ok (i.e. all current versions are >= compatibility versions). I ran `otool -L` on each of the above and the versions again look fine for each. Aside from versions, is there anything else I should be looking out for?

My current best bet will be to work my way through [this](https://www.ibm.com/developerworks/data/library/techarticle/dm-1108odbcdrivermanager/index.html). Very appreciative of any additional tips or pointers you may have

NB For the sake of completeness, I also reinstalled some other versions of R (`3.3.3` and `4.0.0`) to see if anything was different, but nothing changed (same error message), confirming it's solely a driver issue

**Comment by mzj109** [comment] 2020-04-29 17:00
Hi @stevecondylios 
Fwiw, I had a similar issue with R/odbc: "file not found".
The "strings" command did not reveal anything useful. All libraries listed in strings output were correctly situated.
I resorted to "strace". e.g. strace -p [PID or R process]

This revealed -1 ENOENT (No such file or directory) for a particular vendor odbc .so dependency (not the main driver file). Strace could not find the file in several places, even though the file was clearly in LD_LIBRARY_PATH.  After finding this, a simple symlink fixed the issue .

Hope this helps.
mzj109

**Comment by jimhester** [comment] 2020-05-01 12:14
As you have both discovered, `file not found` errors like this are coming from the shared library trying to load the driver shared libraries. They are not errors in the odbc package itself, therefore I will close this issue.

**Closed by jimhester** 2020-05-01 12:14 UTC

**Comment by paul-goodall** [comment] 2021-09-29 03:28
Hi @mzj109 - apologies for going over very old ground here - but I'm having this same problem:

`Error: nanodbc/nanodbc.cpp:1021: 00000: [unixODBC][Driver Manager]Can't open lib '/Library/simba/sqlserverodbc/lib/libsqlserverodbc_sbu.dylib' : file not found`

even though libsqlserverodbc_sbu.dylib does exist in that location.  Are you able to remember exactly what symlinks you created to solve the issue?  Any help would be appreciated.

**Comment by k-paz** [comment] 2023-10-05 19:31
This **BUG still remains** after so many years and it is **UNSOLVED**, so the **case should be reopened and assigned to development fix**, while it happens on different systems with different databases and R/Studio versions even today -> I've just installed current ones of:
```
R version 4.3.1 (2023-06-16) -- "Beagle Scouts"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin20 (64-bit)

RStudio
2023.09.0 Build 463
© 2009-2023 Posit Software, PBC
"Desert Sunflower" Release (b51c81cc, 2023-09-25) for macO
```

and IBM DB2 ODBC driver 11.5.8 that is configured properly and working in the system from command line/bash with the remote IBM Db2 DWH 11.5.7 Server, but RStudio is unable to load the driver library due to this unresolved BUG.

```
> library(DBI)
> system("file /Applications/dsdriver/lib/libdb2o.dylib")
/Applications/dsdriver/lib/libdb2o.dylib: Mach-O 64-bit dynamically linked shared library x86_64
> con <- dbConnect(odbc::odbc(), "BLUDB", timeout = 10)
Error: nanodbc/nanodbc.cpp:1135: 00000: [unixODBC][Driver Manager]Can't open lib '/Applications/dsdriver/lib/libdb2o.dylib' : file not found 
> system("otool -L /Applications/dsdriver/lib/libdb2o.dylib")
/Applications/dsdriver/lib/libdb2o.dylib:
	libdb2o.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1677.104.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/gcc@8/lib/gcc/8/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.25.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	/usr/local/lib/gcc/8/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
> version
               _                           
platform       x86_64-apple-darwin20       
arch           x86_64                      
os             darwin20                    
system         x86_64, darwin20            
status                                     
major          4                           
minor          3.1                         
year           2023                        
month          06                          
day            16                          
svn rev        84548                       
language       R                           
version.string R version 4.3.1 (2023-06-16)
nickname       Beagle Scouts               
```

**Please reopen and solve this over 3 years old problem in R.**


Regards,
Kris.

> Hi @mzj109 - apologies for going over very old ground here - but I'm having this same problem:
> 
> `Error: nanodbc/nanodbc.cpp:1021: 00000: [unixODBC][Driver Manager]Can't open lib '/Library/simba/sqlserverodbc/lib/libsqlserverodbc_sbu.dylib' : file not found`
> 
> even though libsqlserverodbc_sbu.dylib does exist in that location. Are you able to remember exactly what symlinks you created to solve the issue? Any help would be appreciated.

**Comment by WShulerC** [comment] 2024-07-16 15:03
@paul-goodall I know it's been 3 years but any success?
