### ISSUE TITLE
Issue creating local temporary table in SQL Server dB using Select Into SQL statement

### ISSUE THREAD

**Issue by kerry-ja** [r-dbi/odbc#127] opened 2017-10-26 10:50 UTC
### Issue Description and Expected Result
When I try to create a local temporary table in a SQL Server database using the Select into SQL statement, I would expect that the table would be created, and could later be queried or read or dropped, as can be done for a global temporary table, or a non-temporary table, instead an error is generated when trying to read  or query or drop the table 

### Database
Microsoft SQL Server 2014 (SP1-CU5) (KB3130926) - 12.0.4439.1 (X64) 
 Feb 15 2016 12:12:43 
 Copyright (c) Microsoft Corporation
 Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: )

### Reproducible Example
``` r
serverName <- "Server Name"
dBname <- "Database Name"

library(odbc)
library(DBI)
library(dbplyr)

con <-
  dbConnect(odbc::odbc(),
            driver = "{SQL Server}",
            server = serverName,
            database = dBname)

# Create 3 tables in SQL Server database; a local temporary, a global temporary and a non-temporary 
# using  The SQL SELECT INTO Statement where the table type is determined by number of pound signs in table name (none for non-temp table)
dbExecute(con, "Select 'Local Temp Table' as TableType into #LocalTemp;
          Select 'Global Temp Table' as TableType into ##GlobalTemp;
          Select 'Non-Temp Table' as TableType into NonTemp;
          ")
#> [1] 1

# Query the tables, and see what the response is
dbGetQuery(con, "Select * from #LocalTemp")
#> Error: <SQL> 'Select * from #LocalTemp'
#>   nanodbc/nanodbc.cpp:1587: 42S02: [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name '#LocalTemp'.
dbGetQuery(con, "Select * from ##GlobalTemp")
#>           TableType
#> 1 Global Temp Table
dbGetQuery(con, "Select * from NonTemp")
#>        TableType
#> 1 Non-Temp Table

# Read the tables, and see what the response is
dbReadTable(con, "#LocalTemp")
#> Error: <SQL> 'SELECT * FROM "#LocalTemp"'
#>   nanodbc/nanodbc.cpp:1587: 42S02: [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name '#LocalTemp'.
dbReadTable(con, "##GlobalTemp")
#>           TableType
#> 1 Global Temp Table
dbReadTable(con, "NonTemp")
#>        TableType
#> 1 Non-Temp Table

# Drop the tables
dbRemoveTable(con,"#LocalTemp")
#> Error: <SQL> 'DROP TABLE  "#LocalTemp"'
#>   nanodbc/nanodbc.cpp:1587: 42S02: [Microsoft][ODBC SQL Server Driver][SQL Server]Cannot drop the table '#LocalTemp', because it does not exist or you do not have permission.
dbRemoveTable(con,"##GlobalTemp")
dbRemoveTable(con,"NonTemp")

# Disconnect
dbDisconnect(con)

# See what the session info is
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.4.2 (2017-09-28)
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  tz       America/New_York            
#>  date     2017-10-26
#> Packages -----------------------------------------------------------------
#>  package    * version    date       source                            
#>  assertthat   0.2.0      2017-04-11 CRAN (R 3.4.0)                    
#>  backports    1.1.1      2017-09-25 CRAN (R 3.4.1)                    
#>  base       * 3.4.2      2017-09-28 local                             
#>  bindr        0.1        2016-11-13 CRAN (R 3.4.0)                    
#>  bindrcpp     0.2        2017-06-17 CRAN (R 3.4.0)                    
#>  bit          1.1-12     2014-04-09 CRAN (R 3.4.0)                    
#>  bit64        0.9-7      2017-05-08 CRAN (R 3.4.0)                    
#>  blob         1.1.0      2017-06-17 CRAN (R 3.4.0)                    
#>  compiler     3.4.2      2017-09-28 local                             
#>  datasets   * 3.4.2      2017-09-28 local                             
#>  DBI        * 0.7-12     2017-10-24 Github (rstats-db/DBI@f8c97f2)    
#>  dbplyr     * 1.1.0.9000 2017-10-26 Github (tidyverse/dbplyr@3bdee6a) 
#>  devtools     1.13.3     2017-08-02 CRAN (R 3.4.1)                    
#>  digest       0.6.12     2017-01-27 CRAN (R 3.4.0)                    
#>  dplyr        0.7.4      2017-09-28 CRAN (R 3.4.2)                    
#>  evaluate     0.10.1     2017-06-24 CRAN (R 3.4.1)                    
#>  glue         1.1.1      2017-06-21 CRAN (R 3.4.0)                    
#>  graphics   * 3.4.2      2017-09-28 local                             
#>  grDevices  * 3.4.2      2017-09-28 local                             
#>  hms          0.3        2016-11-22 CRAN (R 3.4.0)                    
#>  htmltools    0.3.6      2017-04-24 Github (rstudio/htmltools@4fbf990)
#>  knitr        1.17       2017-08-10 CRAN (R 3.4.1)                    
#>  magrittr     1.5        2014-11-22 CRAN (R 3.4.0)                    
#>  memoise      1.1.0      2017-04-21 CRAN (R 3.4.0)                    
#>  methods    * 3.4.2      2017-09-28 local                             
#>  odbc       * 1.1.3.9000 2017-10-24 Github (rstats-db/odbc@b3d159a)   
#>  pkgconfig    2.0.1      2017-03-21 CRAN (R 3.4.0)                    
#>  R6           2.2.2      2017-06-17 CRAN (R 3.4.0)                    
#>  Rcpp         0.12.13    2017-09-28 CRAN (R 3.4.1)                    
#>  rlang        0.1.2      2017-08-09 CRAN (R 3.4.1)                    
#>  rmarkdown    1.6        2017-06-15 CRAN (R 3.4.0)                    
#>  rprojroot    1.2        2017-01-16 CRAN (R 3.4.0)                    
#>  stats      * 3.4.2      2017-09-28 local                             
#>  stringi      1.1.5      2017-04-07 CRAN (R 3.4.0)                    
#>  stringr      1.2.0      2017-02-18 CRAN (R 3.4.0)                    
#>  tibble       1.3.4      2017-08-22 CRAN (R 3.4.1)                    
#>  tools        3.4.2      2017-09-28 local                             
#>  utils      * 3.4.2      2017-09-28 local                             
#>  withr        2.0.0      2017-07-28 CRAN (R 3.4.1)                    
#>  yaml         2.1.14     2016-11-12 CRAN (R 3.4.0)
```

**Comment by kerry-ja** [comment] 2017-11-21 21:03
``` r
serverName <- "server name
dBname <- "db name"

library(odbc)
library(DBI)
library(dbplyr)

con <-
  dbConnect(odbc::odbc(),
            driver = "{SQL Server}",
            server = serverName,
            database = dBname)

# Create 3 tables in SQL Server database; a local temporary, a global temporary and a non-temporary 
# using  The SQL SELECT INTO Statement where the table type is determined by number of pound signs in table name (none for non-temp table)
dbExecute(con, "Select 'Local Temp Table' as TableType into #LocalTemp;
          Select 'Global Temp Table' as TableType into ##GlobalTemp;
          Select 'Non-Temp Table' as TableType into NonTemp;
          ")
#> [1] 1

# Query the tables, and see what the response is
dbGetQuery(con, "Select * from #LocalTemp")
#> Error: <SQL> 'Select * from #LocalTemp'
#>   nanodbc/nanodbc.cpp:1587: 42S02: [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name '#LocalTemp'.
dbGetQuery(con, "Select * from ##GlobalTemp")
#>           TableType
#> 1 Global Temp Table
dbGetQuery(con, "Select * from NonTemp")
#>        TableType
#> 1 Non-Temp Table

# Read the tables, and see what the response is
dbReadTable(con, "#LocalTemp")
#> Error: <SQL> 'SELECT * FROM "#LocalTemp"'
#>   nanodbc/nanodbc.cpp:1587: 42S02: [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name '#LocalTemp'.
dbReadTable(con, "##GlobalTemp")
#>           TableType
#> 1 Global Temp Table
dbReadTable(con, "NonTemp")
#>        TableType
#> 1 Non-Temp Table

# Drop the tables
dbRemoveTable(con,"#LocalTemp")
#> Error: <SQL> 'DROP TABLE  "#LocalTemp"'
#>   nanodbc/nanodbc.cpp:1587: 42S02: [Microsoft][ODBC SQL Server Driver][SQL Server]Cannot drop the table '#LocalTemp', because it does not exist or you do not have permission.
dbRemoveTable(con,"##GlobalTemp")
dbRemoveTable(con,"NonTemp")

# See what the session info, OS and driver are
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.4.2 (2017-09-28)
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  tz       America/New_York            
#>  date     2017-11-21
#> Packages -----------------------------------------------------------------
#>  package    * version    date       source                            
#>  assertthat   0.2.0      2017-04-11 CRAN (R 3.4.0)                    
#>  backports    1.1.1      2017-09-25 CRAN (R 3.4.1)                    
#>  base       * 3.4.2      2017-09-28 local                             
#>  bindr        0.1        2016-11-13 CRAN (R 3.4.0)                    
#>  bindrcpp     0.2        2017-06-17 CRAN (R 3.4.0)                    
#>  bit          1.1-12     2014-04-09 CRAN (R 3.4.0)                    
#>  bit64        0.9-7      2017-05-08 CRAN (R 3.4.0)                    
#>  blob         1.1.0      2017-06-17 CRAN (R 3.4.0)                    
#>  compiler     3.4.2      2017-09-28 local                             
#>  datasets   * 3.4.2      2017-09-28 local                             
#>  DBI        * 0.7-12     2017-11-13 Github (rstats-db/DBI@6c111b7)    
#>  dbplyr     * 1.1.0.9000 2017-11-21 Github (tidyverse/dbplyr@a424f67) 
#>  devtools     1.13.4     2017-11-09 CRAN (R 3.4.2)                    
#>  digest       0.6.12     2017-01-27 CRAN (R 3.4.0)                    
#>  dplyr        0.7.4      2017-09-28 CRAN (R 3.4.2)                    
#>  evaluate     0.10.1     2017-06-24 CRAN (R 3.4.1)                    
#>  glue         1.2.0      2017-10-29 CRAN (R 3.4.2)                    
#>  graphics   * 3.4.2      2017-09-28 local                             
#>  grDevices  * 3.4.2      2017-09-28 local                             
#>  hms          0.3        2016-11-22 CRAN (R 3.4.0)                    
#>  htmltools    0.3.6      2017-04-24 Github (rstudio/htmltools@4fbf990)
#>  knitr        1.17       2017-08-10 CRAN (R 3.4.1)                    
#>  magrittr     1.5        2014-11-22 CRAN (R 3.4.0)                    
#>  memoise      1.1.0      2017-04-21 CRAN (R 3.4.0)                    
#>  methods    * 3.4.2      2017-09-28 local                             
#>  odbc       * 1.1.3.9000 2017-10-24 Github (rstats-db/odbc@b3d159a)   
#>  pillar       0.0.0.9000 2017-11-21 Github (r-lib/pillar@5a082e1)     
#>  pkgconfig    2.0.1      2017-03-21 CRAN (R 3.4.0)                    
#>  R6           2.2.2      2017-06-17 CRAN (R 3.4.0)                    
#>  Rcpp         0.12.13    2017-09-28 CRAN (R 3.4.1)                    
#>  rlang        0.1.4      2017-11-05 CRAN (R 3.4.2)                    
#>  rmarkdown    1.7        2017-11-10 CRAN (R 3.4.2)                    
#>  rprojroot    1.2        2017-01-16 CRAN (R 3.4.0)                    
#>  stats      * 3.4.2      2017-09-28 local                             
#>  stringi      1.1.5      2017-04-07 CRAN (R 3.4.0)                    
#>  stringr      1.2.0      2017-02-18 CRAN (R 3.4.0)                    
#>  tibble       1.3.4.9003 2017-11-21 Github (tidyverse/tibble@60281b3) 
#>  tools        3.4.2      2017-09-28 local                             
#>  utils      * 3.4.2      2017-09-28 local                             
#>  withr        2.1.0      2017-11-01 CRAN (R 3.4.2)                    
#>  yaml         2.1.14     2016-11-12 CRAN (R 3.4.0)
Sys.info() 
#>                      sysname                      release 
#>                    "Windows"                      "7 x64" 
#>                      version                     nodename 
#> "build 7601, Service Pack 1"                "computer name" 
#>                      machine                        login 
#>                     "x86-64"              "kerry.ja" 
#>                         user               effective_user 
#>              "kerry.ja"              "kerry.ja"
dbGetInfo(con)
#> $dbname
#> [1] "db name"
#> 
#> $dbms.name
#> [1] "Microsoft SQL Server"
#> 
#> $db.version
#> [1] "12.00.4439"
#> 
#> $username
#> [1] "kerryja"
#> 
#> $host
#> [1] ""
#> 
#> $port
#> [1] ""
#> 
#> $sourcename
#> [1] ""
#> 
#> $servername
#> [1] "server name"
#> 
#> $drivername
#> [1] "SQLSRV32.DLL"
#> 
#> $odbc.version
#> [1] "03.80.0000"
#> 
#> $driver.version
#> [1] "06.01.7601"
#> 
#> $odbcdriver.version
#> [1] "03.52"
#> 
#> $supports.transactions
#> [1] TRUE
#> 
#> attr(,"class")
#> [1] "Microsoft SQL Server" "driver_info"          "list"

# Disconnect
dbDisconnect(con)
```

**Comment by daattali** [comment] 2018-02-18 17:25
I get the error as well. I can only create global temp tables, not local.

```
library(DBI)
con <- DBI::dbConnect(
    odbc::odbc(),
    Driver = "{SQL Server}",
    Server = "localhost\\SQLEXPRESS",
    Database = database
)

# Create a global temp table and read from it
dbExecute(con,
  "CREATE TABLE ##deantest1 (TableType varchar(255));
  INSERT INTO ##deantest1 VALUES ('test');")
dbReadTable(con, "##deantest1")
```

That works fine, gives me this output:

```
  TableType
1      test
```

But when I try to do a local temp table

```
dbExecute(con,
  "CREATE TABLE #deantest2 (TableType varchar(255));
  INSERT INTO #deantest2 VALUES ('test');")
```

I get error

```
Error: <SQL> 'SELECT * FROM "#deantest2"'
  nanodbc/nanodbc.cpp:1587: 42S02: [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name '#deantest2'.
```

---

```
> devtools::session_info()
Session info --------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, mingw32             
 ui       RStudio (1.1.414)           
 language (EN)                        
 collate  English_Canada.1252         
 tz       America/New_York            
 date     2018-02-18                  

Packages ------------------------------------------------------------------------------
 package   * version    date       source                          
 base      * 3.4.3      2017-12-06 local                           
 bit         1.1-12     2014-04-09 CRAN (R 3.4.1)                  
 bit64       0.9-7      2017-05-08 CRAN (R 3.4.1)                  
 blob        1.1.0      2017-06-17 CRAN (R 3.4.3)                  
 compiler    3.4.3      2017-12-06 local                           
 datasets  * 3.4.3      2017-12-06 local                           
 DBI       * 0.7        2017-06-18 CRAN (R 3.4.3)                  
 devtools    1.13.4     2017-11-09 CRAN (R 3.4.3)                  
 digest      0.6.15     2018-01-28 CRAN (R 3.4.3)                  
 graphics  * 3.4.3      2017-12-06 local                           
 grDevices * 3.4.3      2017-12-06 local                           
 hms         0.4.0      2017-11-23 CRAN (R 3.4.3)                  
 memoise     1.1.0      2017-04-21 CRAN (R 3.4.3)                  
 methods   * 3.4.3      2017-12-06 local                           
 odbc        1.1.5      2018-01-23 CRAN (R 3.4.3)                  
 pillar      1.1.0      2018-01-14 CRAN (R 3.4.3)                  
 pkgconfig   2.0.1      2017-03-21 CRAN (R 3.4.3)                  
 Rcpp        0.12.15    2018-01-20 CRAN (R 3.4.3)                  
 rlang       0.1.6.9003 2018-02-09 Github (tidyverse/rlang@616fd4d)
 stats     * 3.4.3      2017-12-06 local                           
 tibble      1.4.2      2018-01-22 CRAN (R 3.4.3)                  
 tools       3.4.3      2017-12-06 local                           
 utils     * 3.4.3      2017-12-06 local                           
 withr       2.1.1      2017-12-19 CRAN (R 3.4.3)                  
 yaml        2.1.16     2017-12-12 CRAN (R 3.4.3)
```

**Comment by jimhester** [comment] 2018-03-21 20:36
I am not positive this is actually a bug in the package, will try to reproduce this when I can get a SQLServer setup again.

**Comment by aryoda** [comment] 2018-06-10 20:49
Could be caused by connection pooling. Try to disable connection pooling in the ODBC settings or connection string (can't remember the exact steps ATM)

**Comment by kerry-ja** [comment] 2018-06-11 12:07
I still have this issue with connection pooling disabled.  I tried adding `ConnectionPooling=FALSE` to the connection string, and I was able to connect to the database without issue, however I still have the same issue when trying to create a local temp table.  I then tried going to the connection pooling tab of the ODBC Data Source Administrator, and saw that for the SQL Server driver the PerfMon is set to Disable.  Does this mean the Connection Pooling for this driver is disabled?
![image](https://user-images.githubusercontent.com/25394804/41230341-6e0b09e2-6d4d-11e8-9a63-92591bfc45d6.png)

I also tried to disable connection pooling by adding `"{OLE DB Services}" = -2` to the connection based on what it says at [https://msdn.microsoft.com/en-us/library/ms810829.aspx](https://msdn.microsoft.com/en-us/library/ms810829.aspx), and it was the same result; I was able to connect to the database without issue, however I still have the same issue when trying to create a local temp table.

**Comment by aryoda** [comment] 2018-06-11 18:11
Adding "ConnectionPooling=false;" to the connection string was just my guess and seems to be wrong.

Setting "PerfMon" to "Disable" does **not** disable the connection pooling but only the performance monitoring.

To disable the connection pool you have to **double click** on the driver name (thanks for hiding this, M$ ;-)

![disable_odbc_connection_pooling](https://user-images.githubusercontent.com/11374410/41249163-9543a274-6db3-11e8-85be-c93914483300.png)

**Comment by kerry-ja** [comment] 2018-06-11 18:31
Thanks for the details on how to disable pooled connections for a driver.  

I set the properties for the SQL Server driver to Don't pool connections to this driver and reran the code.  I still have the issue where I am unable to create a local temporary table.

**Comment by aryoda** [comment] 2018-06-11 18:38
I can reproduce your problem under various scenarios (see my test variations at the end) and switching off the connection pool does **not** solve the problem.

The real reason is:

`odbc` sends this type of SQL code to the SQL Server to prepare a SQL statement and bind the parameters then (I have used the SQL Server Profiler to "sniff" the traffic):

```
declare @p1 int
set @p1=1
exec sp_prepexec @p1 output,NULL,N'Select ''Local Temp Table'' as TableType into #LocalTemp;
                select * from #LocalTemp'
select @p1
exec sp_unprepare 1
```

The `sp_prepexec` seems to execute the SQL in a new "scope" which hides the created temp table. This is not documented well, but some info is here:
https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-prepexec-transact-sql?view=sql-server-2017

When I execute this code in SSMS I can reproduce the "out-of-scope" temp table:

```
declare @p1 int
exec sp_prepexec @p1 output,NULL,N'Select ''Local Temp Table'' as TableType into #LocalTemp;
                select * from tempdb..#LocalTemp'
-- correctly returns the content of temp table as result:
-- TableType
-- Local Temp Table
select * from #LocalTemp
-- Msg 208, Level 16, State 0, Line 11
-- Invalid object name '#LocalTemp'.
select @p1   -- show the handle assigned by calling sp_prepexec
exec sp_unprepare @p1
select * from #LocalTemp
-- Msg 208, Level 16, State 0, Line 17
-- Invalid object name '#LocalTemp'.
```

**Options: Either this is classified as bug, documented as know limitation or an argument is added to the `db*` functions to send the SQL as-is instead of calling sp_prepexec`.**

PS: My test variations (all resulting in the same error messages):

```
dbGetQuery(con, "Select * from #LocalTemp")
# Error: <SQL> 'Select * from #LocalTemp'
#  nanodbc/nanodbc.cpp:1587: 42S02: [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid object name '#LocalTemp'.

dbGetQuery(con, "Select 'Local Temp Table' as TableType into #LocalTemp;
                select * from tempdb..#LocalTemp")
dbGetQuery(con, "Select 'Local Temp Table' as TableType into #LocalTemp;")
dbGetQuery(con, "select * from #LocalTemp")
dbGetQuery(con, "select * from tempdb..#LocalTemp")
```

I have also used another driver (`{SQL Server Native Client 11.0}`) with the same results (lost temp table).

**Comment by ismirsehregal** [comment] 2018-10-04 10:44
Any news on this? I'm having the same problem.

**Comment by ericjb** [comment] 2018-10-11 09:08
+1 I am also having this problem using MS SQL Server via odbc (in R). Please fix.

**Comment by kokheng1025** [comment] 2018-10-23 07:05
I'm having the same problem, any newsfor this issue?

**Comment by nwstephens** [comment] 2018-11-25 20:47
@jimhester I can create local temp tables with `dbSendQuery` but they do not show up with `dbExistTable`. I am able to create global temp tables with `dbWriteTable` but not local temp tables. Simba verified that this is not a driver problem. I agree with @aryoda: this should either be marked as limitation or [better] we should fix.

```
# Install latest RStudio release of the SQL Server ODBC driver
# in RStudio
# install odbc if not installed
install.packages("odbc")
# load library
library(odbc)
# make connection to MS SQL Server
con <- dbConnect(odbc(), Driver = "Simba SQL Server ODBC Driver", Server = <host>, Database = "temporal", UID = <user>, PWD = <password>, Port = 1433)

# try to create a local temporary table
#dbWriteTable(con, "#tempmtcars", mtcars) # this command throws an error

# this version will run
dbSendQuery(con, "CREATE TABLE #employees ( employee_id INT PRIMARY KEY,
			last_name VARCHAR(50) NOT NULL,
            first_name VARCHAR(50),
            salary MONEY )")
# but when queried it doesn't exist
dbExistsTable(con, "#employees") # this returns false

# a global temporary table is created in the same way but by putting two "#" in front of the table name
```

**Comment by cas397** [comment] 2019-01-15 21:02
For anyone still having an issue with this, I found a work around online originally intended for the RODBC package. Inserting the following line at the beginning of your sql query allowed R to retain the temp tables.

set nocount on

I have to caveat this with the fact I typically keep my query saved as a text or .sql file. And then read it in using the readLines & paste functions. So I inserted this at the very beginning of my text file that contained the query and saved it. Then I ran the code below and had no issues with the temp table.

connection <- dbConnect(drv = odbc(), dsn = "server name", database = "database name")
daily_otp_query <- readLines(con = "~/Daily OTP Stats.sql")
daily_otp_query <- paste(daily_otp_query, collapse = "\n")
daily_otp <- dbGetQuery(conn = connection, statement = daily_otp_query)

As for WHY reading temp tables causes issues, the following link gives the explanation below. https://stackoverflow.com/questions/4747768/rodbc-temporary-table-issue-when-connecting-to-ms-sql-server

The RODBC driver seems to think that when SQL Server returns any count of rows that the entire statement is complete. So you need to set nocount on at the beginning of your statement or stored procedure that is called.

**Comment by krlmlr** [comment] 2019-04-10 05:33
I'm seeing the same behavior when trying this with `isql` on the same ODBC connection. `SET NOCOUNT ON` doesn't help, neither with R, nor with `isql`.

```sh
echo '
SELECT 1 AS a INTO #test
SELECT * FROM #test
SELECT 1 AS a INTO #test
' | isql -k '<connection string>'
# SQL> SELECT 1 AS a INTO #test
# SQLRowCount returns 1
# SQL> SELECT * FROM #test
# [ISQL]ERROR: Could not SQLExecute
# SQL> SELECT 1 AS a INTO #test
# SQLRowCount returns 1
```

However, the `-e` switch with `isql` works:

```sh
echo '
SELECT 1 AS a INTO #test
SELECT * FROM #test
SELECT 1 AS a INTO #test
' | isql -e -k '<connection string>'
# SQL> SELECT 1 AS a INTO #test
# SQLRowCount returns 1
# SQL> SELECT * FROM #test
# +------------+
# | a          |
# +------------+
# | 1          |
# +------------+
# SQLRowCount returns 1
# 1 rows fetched
# SQL> SELECT 1 AS a INTO #test
# [ISQL]ERROR: Could not SQLExecDirect
```

The `-e` switch in `isql` instructs it to use `SQLExecDirect` instead of `Prepare`. The MSSQL documentation indicates that temporaray tables are also limitied to the scope of the procedure or transaction that creates them, the behavior starts to make sense.

When DBI gains `dbSendQueryNow()` and `dbSendStatementNow()` (r-dbi/DBI#268), we will have more control over the behavior here.

**Comment by krlmlr** [comment] 2019-04-15 22:18
#163 is related.

**Comment by shrektan** [comment] 2019-07-24 10:11
Bite by this issue, too. Local temp table can't be created. Global temp table can be created but can't be found in `dbExistsTable()` results in failure when trying to append data to it with `dbWriteTable()`.

**Comment by nwstephens** [comment] 2019-07-24 19:02
I've reached out to our driver vendor requesting more information about potential options.

**Comment by krlmlr** [comment] 2019-07-24 19:05
We need to use direct queries instead of prepared queries for local temporary tables. This is very high on my list of priorities but still might take some time.

**Comment by nwstephens** [comment] 2019-07-24 21:28
Thanks, @krlmlr, I wasn't sure if there was another solution, but agree a DBI fix would the preferred solution. Thanks for the update.

**Closed** 2019-11-21 17:06 UTC
Labels: bug, mssql

**Comment by Calsimeth** [comment] 2020-07-17 14:49
I am still having this problem.

**Comment by aryoda** [comment] 2020-07-20 06:34
> I am still having this problem.

Can you please add a minimal reproducible example of your code + the `sessionInfo()` output?

BTW: If it is not exactly the same problem then it would be better to open a new issue (referencing this) instead of using an already closed issue...

**Comment by kerry-ja** [comment] 2020-07-20 10:56
I am still having this issue as well.

``` r
serverName <- "Server Name"
dBname <- "DB Name"

library(odbc)
library(DBI)
library(dbplyr)

con <-
dbConnect(odbc::odbc(),
driver = "{SQL Server}",
server = serverName,
database = dBname,
ConnectionPooling=FALSE)

# Create 3 tables in SQL Server database; a local temporary, a global temporary and a non-temporary 
# using  The SQL SELECT INTO Statement where the table type is determined by number of pound signs in table name (none for non-temp table)
dbExecute(con, "Select 'Local Temp Table' as TableType into #LocalTemp;
Select 'Global Temp Table' as TableType into ##GlobalTemp;
Select 'Non-Temp Table' as TableType into NonTemp;
")
#> [1] 1

# Query the tables, and see what the response is
dbGetQuery(con, "Select * from #LocalTemp")
#> Error: nanodbc/nanodbc.cpp:1617: 42000: [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name '#LocalTemp'.  [Microsoft][ODBC SQL Server Driver][SQL Server]Statement(s) could not be prepared. 
#> <SQL> 'Select * from #LocalTemp'
dbGetQuery(con, "Select * from ##GlobalTemp")
#>           TableType
#> 1 Global Temp Table
dbGetQuery(con, "Select * from NonTemp")
#>        TableType
#> 1 Non-Temp Table

# Read the tables, and see what the response is
dbReadTable(con, "#LocalTemp")
#> Error: nanodbc/nanodbc.cpp:1617: 42000: [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name '#LocalTemp'.  [Microsoft][ODBC SQL Server Driver][SQL Server]Statement(s) could not be prepared. 
#> <SQL> 'SELECT * FROM "#LocalTemp"'
dbReadTable(con, "##GlobalTemp")
#>           TableType
#> 1 Global Temp Table
dbReadTable(con, "NonTemp")
#>        TableType
#> 1 Non-Temp Table

# Drop the tables
dbRemoveTable(con,"#LocalTemp")
#> Error: nanodbc/nanodbc.cpp:1617: 42S02: [Microsoft][ODBC SQL Server Driver][SQL Server]Cannot drop the table '#LocalTemp', because it does not exist or you do not have permission. 
#> <SQL> 'DROP TABLE  "#LocalTemp"'
dbRemoveTable(con,"##GlobalTemp")
dbRemoveTable(con,"NonTemp")

# See what the session info, OS and driver are
devtools::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.0.2 (2020-06-22)
#>  os       Windows 7 x64 SP 1          
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       America/New_York            
#>  date     2020-07-20                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version  date       lib source        
#>  assertthat    0.2.1    2019-03-21 [1] CRAN (R 4.0.0)
#>  backports     1.1.8    2020-06-17 [1] CRAN (R 4.0.1)
#>  bit           1.1-15.2 2020-02-10 [1] CRAN (R 4.0.0)
#>  bit64         0.9-7.1  2020-07-15 [1] CRAN (R 4.0.2)
#>  blob          1.2.1    2020-01-20 [1] CRAN (R 4.0.0)
#>  callr         3.4.3    2020-03-28 [1] CRAN (R 4.0.0)
#>  cli           2.0.2    2020-02-28 [1] CRAN (R 4.0.0)
#>  crayon        1.3.4    2017-09-16 [1] CRAN (R 4.0.0)
#>  DBI         * 1.1.0    2019-12-15 [1] CRAN (R 4.0.0)
#>  dbplyr      * 1.4.4    2020-05-27 [1] CRAN (R 4.0.0)
#>  desc          1.2.0    2018-05-01 [1] CRAN (R 4.0.0)
#>  devtools      2.3.0    2020-04-10 [1] CRAN (R 4.0.0)
#>  digest        0.6.25   2020-02-23 [1] CRAN (R 4.0.0)
#>  dplyr         1.0.0    2020-05-29 [1] CRAN (R 4.0.0)
#>  ellipsis      0.3.1    2020-05-15 [1] CRAN (R 4.0.0)
#>  evaluate      0.14     2019-05-28 [1] CRAN (R 4.0.0)
#>  fansi         0.4.1    2020-01-08 [1] CRAN (R 4.0.0)
#>  fs            1.4.2    2020-06-30 [1] CRAN (R 4.0.2)
#>  generics      0.0.2    2018-11-29 [1] CRAN (R 4.0.0)
#>  glue          1.4.1    2020-05-13 [1] CRAN (R 4.0.0)
#>  highr         0.8      2019-03-20 [1] CRAN (R 4.0.0)
#>  hms           0.5.3    2020-01-08 [1] CRAN (R 4.0.0)
#>  htmltools     0.5.0    2020-06-16 [1] CRAN (R 4.0.1)
#>  knitr         1.29     2020-06-23 [1] CRAN (R 4.0.2)
#>  lifecycle     0.2.0    2020-03-06 [1] CRAN (R 4.0.0)
#>  magrittr      1.5      2014-11-22 [1] CRAN (R 4.0.0)
#>  memoise       1.1.0    2017-04-21 [1] CRAN (R 4.0.0)
#>  odbc        * 1.2.3    2020-06-18 [1] CRAN (R 4.0.1)
#>  pillar        1.4.6    2020-07-10 [1] CRAN (R 4.0.2)
#>  pkgbuild      1.1.0    2020-07-13 [1] CRAN (R 4.0.2)
#>  pkgconfig     2.0.3    2019-09-22 [1] CRAN (R 4.0.0)
#>  pkgload       1.1.0    2020-05-29 [1] CRAN (R 4.0.0)
#>  prettyunits   1.1.1    2020-01-24 [1] CRAN (R 4.0.0)
#>  processx      3.4.3    2020-07-05 [1] CRAN (R 4.0.2)
#>  ps            1.3.3    2020-05-08 [1] CRAN (R 4.0.0)
#>  purrr         0.3.4    2020-04-17 [1] CRAN (R 4.0.0)
#>  R6            2.4.1    2019-11-12 [1] CRAN (R 4.0.0)
#>  Rcpp          1.0.5    2020-07-06 [1] CRAN (R 4.0.2)
#>  remotes       2.1.1    2020-02-15 [1] CRAN (R 4.0.0)
#>  rlang         0.4.7    2020-07-09 [1] CRAN (R 4.0.2)
#>  rmarkdown     2.3      2020-06-18 [1] CRAN (R 4.0.1)
#>  rprojroot     1.3-2    2018-01-03 [1] CRAN (R 4.0.0)
#>  sessioninfo   1.1.1    2018-11-05 [1] CRAN (R 4.0.0)
#>  stringi       1.4.6    2020-02-17 [1] CRAN (R 4.0.0)
#>  stringr       1.4.0    2019-02-10 [1] CRAN (R 4.0.0)
#>  testthat      2.3.2    2020-03-02 [1] CRAN (R 4.0.0)
#>  tibble        3.0.3    2020-07-10 [1] CRAN (R 4.0.2)
#>  tidyselect    1.1.0    2020-05-11 [1] CRAN (R 4.0.0)
#>  usethis       1.6.1    2020-04-29 [1] CRAN (R 4.0.0)
#>  vctrs         0.3.2    2020-07-15 [1] CRAN (R 4.0.2)
#>  withr         2.2.0    2020-04-20 [1] CRAN (R 4.0.0)
#>  xfun          0.15     2020-06-21 [1] CRAN (R 4.0.1)
#>  yaml          2.2.1    2020-02-01 [1] CRAN (R 4.0.0)
#> 
#> [1] C:/Program Files/R/R-4.0.2/library
Sys.info() 
#>                      sysname                      release 
#>                    "Windows"                      "7 x64" 
#>                      version                     nodename 
#> "build 7601, Service Pack 1"                "Computer Name" 
#>                      machine                        login 
#>                     "x86-64"              "User" 
#>                         user               effective_user 
#>              "User"              "User"
dbGetInfo(con)
#> $dbname
#> [1] "Database Name"
#> 
#> $dbms.name
#> [1] "Microsoft SQL Server"
#> 
#> $db.version
#> [1] "12.00.5589"
#> 
#> $username
#> [1] "User Name"
#> 
#> $host
#> [1] ""
#> 
#> $port
#> [1] ""
#> 
#> $sourcename
#> [1] ""
#> 
#> $servername
#> [1] "Server Name"
#> 
#> $drivername
#> [1] "SQLSRV32.DLL"
#> 
#> $odbc.version
#> [1] "03.80.0000"
#> 
#> $driver.version
#> [1] "06.01.7601"
#> 
#> $odbcdriver.version
#> [1] "03.52"
#> 
#> $supports.transactions
#> [1] TRUE
#> 
#> $getdata.extensions.any_column
#> [1] FALSE
#> 
#> $getdata.extensions.any_order
#> [1] FALSE
#> 
#> attr(,"class")
#> [1] "Microsoft SQL Server" "driver_info"          "list"

# Disconnect
dbDisconnect(con)
```

<sup>Created on 2020-07-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by chrtro1978** [comment] 2022-05-20 20:22
I used the following which works for now

con <- dbConnect(odbc(), Driver = "SQL Server", Server = "server name", 
                 Database = "_DefaultDb", Trusted_Connection = "True")

dbGetQuery(con, " 
 set nocount on

" , immediate = TRUE)
