### ISSUE TITLE
dbExistsTable() error using Id() with Oracle

### ISSUE THREAD

**Issue by copernican** [r-dbi/odbc#165] opened 2018-03-21 20:40 UTC
With the resolution of #91, I have installed the development version of **`odbc`**. It appears that there may be an issue with using `DBI::Id()` with a connection to Oracle. In the example below, I would expect `dbExistsTable()` to return `TRUE`. The variables `dbq`, `user`, and `pwd` store the TNS service name, username, and password, respectively. The table `DUAL` should exist in the `SYS` schema for all versions of Oracle Database.

```r
con <- DBI::dbConnect(drv = odbc::odbc(), Driver = "Oracle in instantclient_12_2", 
  Dbq = dbq, uid = user, pwd = pwd)

tbl <- DBI::Id(schema = "SYS", table = "DUAL")
nrow(DBI::dbReadTable(con, tbl))
#> [1] 1
DBI::dbExistsTable(con, tbl)
#> Error in connection_sql_tables(conn@ptr, catalog_name = if ("catalog" %in% : nanodbc/nanodbc.cpp:4266: HYC00: [Oracle][ODBC]Optional feature not implemented.
```

Here are the relevant lines from `session_info()`:

```
DBI        * 0.8        2018-03-21 Github (jimhester/DBI@17f7e8f)
odbc       * 1.1.5      2018-03-21 Github (r-dbi/odbc@dc1bbf6)
```

**updated** to use latest Oracle drivers (Instant Client version 12.2.0.1.0)

**Comment by jimhester** [comment] 2018-03-21 21:04
This error is coming from the Oracle Driver, and it is erroring on a call to [SQLTables](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqltables-function) which apparently doesn't support querying by schema? I am not sure.

You might try running `dbListTables()` with various things for `schema_name`, `catalog_name` and `table_name`. Some useful values to try are `NULL`, `%` (which should both be wildcards which match everything) and the table / schema names you show.

**Comment by copernican** [comment] 2018-03-21 23:20
The output of `dbListTables()` looks reasonable. Passing the `schema_name` and `table_name` parameters, I see a variety of objects in the appropriate schemata. Here's the result for the `SYS.DUAL` object. I've also installed the latest Oracle ODBC drivers, confirmed that the original error message is unchanged, and have updated the original comment to reflect.

```r
con <- DBI::dbConnect(drv = odbc::odbc(), Driver = "Oracle in instantclient_12_2", 
  Dbq = dbq, uid = user, pwd = pwd)

DBI::dbListTables(con, schema_name = "SYS", table_name = "DUAL")
#> [1] "DUAL"
```

**Comment by jimhester** [comment] 2019-11-19 21:52
This _may_ be fixed by recent changes in the way that `dbExists()` was implemented.

**Comment by jimhester** [comment] 2020-10-22 18:43
This now seems to be working as intended

```r
library(DBI)
con <- dbConnect(odbc::odbc(), "OracleODBC-19")
id <- DBI::Id(schema = "TEST", table = "mtcars")
dbWriteTable(con, id, mtcars)
dbExistsTable(con, id)
[1] TRUE
data <- dbReadTable(con, id)
dbRemoveTable(con, id)
```

**Closed by jimhester** 2020-10-22 18:43 UTC
Labels: oracle, reprex
