### ISSUE TITLE
odbc doing very odd things with dates

### ISSUE THREAD

**Issue by shapenaji** [r-dbi/odbc#95] opened 2017-07-28 15:30 UTC
### Demo

Differing Date return behavior based on machine. 

On certain machines, for the same query, we get different data types for identical versions of odbc and driver.

And while I understand that not everyone deserves a date, and that some have to rely on the strength of their character, this is getting nutty.

For the purpose of this example, I used two Macs with apparently identical operating systems, both of which install R via homebrew. But my test set included several windows users on windows 10 and 7 and ubuntu 16.04

It is possible that there is some dependent C library that is different between them. This is actually my operating assumption about this issue.

Illustration of issue:

I had several people run this same code:
```r
con <- dbConnect(odbc::odbc(), 'XXXXXXX', 
                               uid = getOption('ODBCuid'), 
                              pwd = getOption('ODBCpwd'), 
                 timezone = 'XXXXXXXX')
out <- dbGetQuery(con, 'select top 1 Date from olap.vdimdates')
print(out)
```

They were split into two camps, those that got character:

```r
> print(out)
        Date
1 1900-01-01
> class(out$Date)
[1] "character"
```

and those who got Date:

```r
> print(out)
        Date
1 1900-01-01
> class(out$Date)
[1] "Date"
```

Further, for those who got Dates, they get dates which have a fractional numeric value:

```r
> as.numeric(out$Date)
[1] -25566.67
```

### Database
```r
> print(con)
<OdbcConnection> XXXXXX
  Database: XXXXXX
  Microsoft SQL Server Version: 13.00.1601
```

<details>
<summary>Session Info</summary>

example of "character" sessioninfo()

```r
devtools::session_info()
Session info ----------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, darwin16.6.0        
 ui       RStudio (1.0.143)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Curacao             
 date     2017-07-28                  

Packages --------------------------------------------------------------------------------------------------------------------------------------------
 package    * version    date       source                         
 base       * 3.4.1      2017-07-18 local                          
 bit          1.1-12     2014-04-09 CRAN (R 3.4.1)                 
 bit64        0.9-7      2017-05-08 CRAN (R 3.4.1)                 
 blob         1.1.0      2017-06-17 CRAN (R 3.4.1)                 
 compiler     3.4.1      2017-07-18 local                          
 curl       * 2.7        2017-06-26 CRAN (R 3.4.1)                 
 datasets   * 3.4.1      2017-07-18 local                          
 DBI        * 0.7        2017-06-18 CRAN (R 3.4.1)                 
 devtools     1.13.2     2017-06-02 CRAN (R 3.4.1)                 
 digest       0.6.12     2017-01-27 CRAN (R 3.4.1)                 
 graphics   * 3.4.1      2017-07-18 local                          
 grDevices  * 3.4.1      2017-07-18 local                          
 hms          0.3        2016-11-22 CRAN (R 3.4.1)                 
 memoise      1.1.0      2017-04-21 CRAN (R 3.4.1)                 
 methods    * 3.4.1      2017-07-18 local                          
 odbc       * 1.1.1.9000 2017-07-28 Github (rstats-db/odbc@5acc553)
 Rcpp         0.12.12    2017-07-15 CRAN (R 3.4.1)                 
 rlang        0.1.1      2017-05-18 CRAN (R 3.4.1)                 
 rstudioapi   0.6        2016-06-27 CRAN (R 3.4.1)                 
 stats      * 3.4.1      2017-07-18 local                          
 tibble       1.3.3      2017-05-28 CRAN (R 3.4.1)                 
 tools        3.4.1      2017-07-18 local                          
 utils      * 3.4.1      2017-07-18 local                          
 withr        1.0.2      2016-06-20 CRAN (R 3.4.1)
```

example of "date" sessionInfo()
```r
> devtools::session_info()
Session info -----------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, darwin16.6.0        
 ui       RStudio (1.0.143)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Curacao             
 date     2017-07-28                  
Packages ---------------------------------------------------------------------------------------------
 package   * version    date       source                         
 base      * 3.4.1      2017-07-07 local                          
 bit         1.1-12     2014-04-09 cran (@1.1-12)                 
 bit64       0.9-7      2017-05-08 cran (@0.9-7)                  
 blob        1.1.0      2017-06-17 CRAN (R 3.4.0)                 
 compiler    3.4.1      2017-07-07 local                          
 curl      * 2.7        2017-06-26 CRAN (R 3.4.1)                 
 datasets  * 3.4.1      2017-07-07 local                          
 DBI       * 0.7        2017-06-18 CRAN (R 3.4.0)                 
 devtools    1.13.2     2017-06-02 CRAN (R 3.4.0)                 
 digest      0.6.12     2017-01-27 CRAN (R 3.4.0)                 
 graphics  * 3.4.1      2017-07-07 local                          
 grDevices * 3.4.1      2017-07-07 local                          
 hms         0.3        2016-11-22 CRAN (R 3.4.0)                 
 memoise     1.1.0      2017-04-21 CRAN (R 3.4.0)                 
 methods   * 3.4.1      2017-07-07 local                          
 odbc      * 1.1.1.9000 2017-07-28 Github (rstats-db/odbc@5acc553)
 Rcpp        0.12.12    2017-07-15 CRAN (R 3.4.1)                 
 rlang       0.1.1      2017-05-18 CRAN (R 3.4.0)                 
 stats     * 3.4.1      2017-07-07 local                          
 tibble      1.3.3      2017-05-28 CRAN (R 3.4.0)                 
 tools       3.4.1      2017-07-07 local                          
 utils     * 3.4.1      2017-07-07 local                          
 withr       1.0.2      2016-06-20 CRAN (R 3.4.0)   
```
</details>

**Comment by shapenaji** [comment] 2017-07-28 15:32
seems related to #61

**Comment by jimhester** [comment] 2017-08-07 13:52
Could you have them run the following rather than reading from a table.

"SELECT 'CAST('2017-01-01' AS date) AS casted_date, CAST('2017-01-01' AS datetime) AS casted_datetime"

Is everyone using the same version of R in these cases?

Also what is the result of

```r
library(DBI)
con <- dbConnect(...)
res <- dbSendQuery(con, "SELECT CAST('2017-01-01' AS date) AS casted_date, CAST('2017-01-01' AS datetime) AS casted_datetime")
odbc:::result_column_info(res@ptr)
str(dbFetch(res))
```

On my machine this results in the following
```r
odbc:::result_column_info(res@ptr)
#>              name type
#> 1     casted_date   91
#> 2 casted_datetime   93
str(dbFetch(res))
#> 'data.frame':   1 obs. of  2 variables:
#>  $ casted_date    : Date, format: "2017-01-01"
#>  $ casted_datetime: POSIXct, format: "2017-01-01"
```

**Comment by shapenaji** [comment] 2017-08-07 16:25
R versions identical (see above `sessionInfo` dropdown)

On my machine (which has been getting dates as character):

```
> con <- dbConnect(odbc::odbc(), data_source, uid = user, pwd = passwd, 
+                  timezone = timezone)
> res <- dbSendQuery(con, "SELECT CAST('2017-01-01' AS date) AS casted_date, CAST('2017-01-01' AS datetime) AS casted_datetime")
> odbc:::result_column_info(res@ptr)
             name type
1     casted_date   -9
2 casted_datetime   93
> str(dbFetch(res))
'data.frame':	1 obs. of  2 variables:
 $ casted_date    : chr "2017-01-01"
 $ casted_datetime: POSIXct, format: "2017-01-01 08:00:00"
```

will confirm shortly on other machine.

**Comment by bjoerm** [comment] 2017-08-07 16:28
I get the same result as @shapenaji:

```r
library(DBI)
library(odbc)
con <- dbConnect(odbc::odbc(),
  # driver = "libtdsodbc.so",
  driver = "{SQL Server}",
  database = "AdventureWorks2012",
  uid = "sqlfamily",
  pwd = "sqlf@m1ly",
  Server = "mhknbn2kdz.database.windows.net",
  port = 1433)

res <- dbSendQuery(con, "SELECT CAST('2017-01-01' AS date) AS casted_date, CAST('2017-01-01' AS datetime) AS casted_datetime")
odbc:::result_column_info(res@ptr)
str(dbFetch(res))
```

```r
> res <- dbSendQuery(con, "SELECT CAST('2017-01-01' AS date) AS casted_date, CAST('2017-01-01' AS datetime) AS casted_datetime")
> odbc:::result_column_info(res@ptr)
             name type
1     casted_date   -9
2 casted_datetime   93
> str(dbFetch(res))
'data.frame':	1 obs. of  2 variables:
 $ casted_date    : chr "2017-01-01"
 $ casted_datetime: POSIXct, format: "2017-01-01"
```

**Comment by marcoblume** [comment] 2017-08-07 16:31
Please remove your credentials @bjoerm

**Comment by shapenaji** [comment] 2017-08-07 16:32
Other machine: (Same specs, also mac, same R version and odbc version)

```r
> odbc:::result_column_info(res@ptr)
             name type
1     casted_date   91
2 casted_datetime   93
> str(dbFetch(res))
'data.frame':    1 obs. of  2 variables:
 $ casted_date    : Date, format: "2017-01-01"
 $ casted_datetime: POSIXct, format: "2017-01-01 08:00:00"
```

**Comment by jimhester** [comment] 2017-08-07 16:52
So a type of -9 is [SQL_WVARCHAR](https://github.com/Microsoft/ODBC-Specification/blob/0583d997331a898bb0077e3cb58e210ced3a5ff1/Windows/inc/sqlucode.h#L28), so this is working correctly as far as the **odbc** package is concerned.

[Microsoft's documentation](https://docs.microsoft.com/en-us/sql/t-sql/data-types/date-transact-sql#backward-compatibility-for-down-level-clients) indicates this conversion is the specified one when the client does not support date objects, so I think the issue lies in what Driver and Driver manager these users have installed.

**Comment by shapenaji** [comment] 2017-08-07 16:58
Like I said, both of us are using same driver, (and driver manager):

On mine:
```
 brew info unixODBC
unixODBC: stable 2.3.4 (bottled)
ODBC 3 connectivity for UNIX
```

```
 brew info freetds
freetds: stable 1.00.48 (bottled), HEAD
Libraries to talk to Microsoft SQL Server and Sybase databases
http://www.freetds.org/
```

`Built from source on 2016-12-07 at 12:41:00 with: --with-unixodbc`

On the other machine:

```
brew info unixodbc
unixodbc: stable 2.3.4 (bottled)
ODBC 3 connectivity for UNIX
http://www.unixodbc.org/
```

```
brew info freetds
freetds: stable 1.00.48 (bottled), HEAD
Libraries to talk to Microsoft SQL Server and Sybase databases
http://www.freetds.org/

```

`Built from source on 2017-07-07 at 09:17:17 with: --with-unixodbc`

**Comment by jimhester** [comment] 2017-08-07 17:14
Can you give the output of the following on both systems.

```r
system(paste("otool -L", system.file(package = "odbc", "libs/odbc.so")))
```

**Comment by shapenaji** [comment] 2017-08-07 17:15
character machine:
```r
> system(paste("otool -L", system.file(package = "odbc", "libs/odbc.so")))
/usr/local/Cellar/r/3.4.1_1/lib/R/library/odbc/libs/odbc.so:
	odbc.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/unixodbc/lib/libodbc.2.dylib (compatibility version 3.0.0, current version 3.0.0)
	/usr/local/opt/r/lib/R/lib/libR.dylib (compatibility version 3.4.0, current version 3.4.1)
	/usr/local/opt/gettext/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.5.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1349.8.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
```

Dates machine:
```r
> system(paste("otool -L", system.file(package = "odbc", "libs/odbc.so")))
/usr/local/lib/R/3.4/site-library/odbc/libs/odbc.so:
    odbc.so (compatibility version 0.0.0, current version 0.0.0)
    /usr/local/opt/unixodbc/lib/libodbc.2.dylib (compatibility version 3.0.0, current version 3.0.0)
    /usr/local/opt/r/R.framework/Versions/3.4/Resources/lib/libR.dylib (compatibility version 3.4.0, current version 3.4.1)
    /usr/local/opt/gettext/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.5.0)
    /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1349.8.0)
    /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
```

**Comment by jimhester** [comment] 2017-08-07 17:19
And if you use the CRAN supplied R rather than the homebrew version?

**Comment by shapenaji** [comment] 2017-08-07 18:50
Sorry for the delay, had to run out for a bit:

After installing from CRAN:
(pretty sure it installed to /usr/local/bin, modification time fits)
```r
> odbc:::result_column_info(res@ptr)
             name type
1     casted_date   -9
2 casted_datetime   93
> str(dbFetch(res))
'data.frame':	1 obs. of  2 variables:
 $ casted_date    : chr "2017-01-01"
 $ casted_datetime: POSIXct, format: "2017-01-01 08:00:00"```

**Comment by jimhester** [comment] 2017-08-07 20:08
And what is the output from the following in a shell

```shell
tsql -Cv
```

Do they have the same values in the config files listed in the `freetds.conf directory`?

**Comment by shapenaji** [comment] 2017-08-07 21:11
Character:
```
XXXXXXX@oz:~$ tsql -Cv
Compile-time settings (established with the "configure" script)
                            Version: freetds v1.00.48
             freetds.conf directory: /usr/local/Cellar/freetds/1.00.48/etc
     MS db-lib source compatibility: no
        Sybase binary compatibility: no
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 7.3
                              iODBC: no
                           unixodbc: yes
              SSPI "trusted" logins: no
                           Kerberos: no
                            OpenSSL: yes
                             GnuTLS: no
                               MARS: no
```

Date:
```[Oriana]:~ XXXXXX$ tsql -Cv
Compile-time settings (established with the "configure" script)
                            Version: freetds v1.00.48
             freetds.conf directory: /usr/local/Cellar/freetds/1.00.48/etc
     MS db-lib source compatibility: no
        Sybase binary compatibility: no
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 7.3
                              iODBC: no
                           unixodbc: yes
              SSPI "trusted" logins: no
                           Kerberos: no
                            OpenSSL: yes
                             GnuTLS: no
                               MARS: no```

**Comment by shapenaji** [comment] 2017-08-07 21:15
freetds.conf looks the same also:



Character: (no modifications were required for install here)
```
XXXXX@oz:~$ cat /usr/local/etc/freetds.conf 
#   $Id: freetds.conf,v 1.12 2007-12-25 06:02:36 jklowden Exp $
#
# This file is installed by FreeTDS if no file by the same 
# name is found in the installation directory.  
#
# For information about the layout of this file and its settings, 
# see the freetds.conf manpage "man freetds.conf".  

# Global settings are overridden by those in a database
# server specific section
[global]
        # TDS protocol version
	tds version = auto

	# Whether to write a TDSDUMP file for diagnostic purposes
	# (setting this to /tmp is insecure on a multi-user system)
;	dump file = /tmp/freetds.log
;	debug flags = 0xffff

	# Command and connection timeouts
;	timeout = 10
;	connect timeout = 10
	
	# If you get out-of-memory errors, it may mean that your client
	# is trying to allocate a huge buffer for a TEXT field.  
	# Try setting 'text size' to a more reasonable limit 
	text size = 64512

	# If you experience TLS handshake errors and are using openssl,
	# try adjusting the cipher list (don't surround in double or single quotes)
	# openssl ciphers = HIGH:!SSLv2:!aNULL:-DH

# A typical Sybase server
[egServer50]
	host = symachine.domain.com
	port = 5000
	tds version = 5.0

# A typical Microsoft server
[egServer70]
	host = ntmachine.domain.com
	port = 1433
	tds version = 7.0
```

Date:
```
[Oriana]:~ XXXXXX$ cat /usr/local/etc/freetds.conf 
#   $Id: freetds.conf,v 1.12 2007-12-25 06:02:36 jklowden Exp $
#
# This file is installed by FreeTDS if no file by the same 
# name is found in the installation directory.  
#
# For information about the layout of this file and its settings, 
# see the freetds.conf manpage "man freetds.conf".  

# Global settings are overridden by those in a database
# server specific section
[global]
        # TDS protocol version
    tds version = auto

    # Whether to write a TDSDUMP file for diagnostic purposes
    # (setting this to /tmp is insecure on a multi-user system)
;    dump file = /tmp/freetds.log
;    debug flags = 0xffff

    # Command and connection timeouts
;    timeout = 10
;    connect timeout = 10
    
    # If you get out-of-memory errors, it may mean that your client
    # is trying to allocate a huge buffer for a TEXT field.  
    # Try setting 'text size' to a more reasonable limit 
    text size = 64512

    # If you experience TLS handshake errors and are using openssl,
    # try adjusting the cipher list (don't surround in double or single quotes)
    # openssl ciphers = HIGH:!SSLv2:!aNULL:-DH

# A typical Sybase server
[egServer50]
    host = symachine.domain.com
    port = 5000
    tds version = 5.0

# A typical Microsoft server
[egServer70]
    host = ntmachine.domain.com
    port = 1433
    tds version = 7.0
```

**Comment by jschelbert** [comment] 2017-08-23 12:25
Same behavior here for Win10 Client running R 3.4.1 with odbc_1.1.1.9000 with connection to a Microsoft SQL Server Version: 12.00.5546 using the standard drivers provided by windows ("SQL Server").
``` r
> res <- dbSendQuery(connection, "SELECT CAST('2017-01-01' AS date) AS casted_date, CAST('2017-01-01' AS datetime) AS casted_datetime")
> odbc:::result_column_info(res@ptr)
             name type
1     casted_date   -9
2 casted_datetime   93
> str(dbFetch(res))
'data.frame':	1 obs. of  2 variables:
 $ casted_date    : chr "2017-01-01"
 $ casted_datetime: POSIXct, format: "2017-01-01"
```

**Comment by jimhester** [comment] 2018-03-21 20:51
I cannot reproduce this locally, and think this is ultimately an issue with the Driver and Driver manager translation rather than a bug in the R package, so am closing this.

**Closed** 2018-03-21 20:50 UTC
